### ISSUE TITLE
Allow multiple pdf viewer tabs of same document

### ISSUE THREAD

**Issue by edgardozoppi** [James-Yu/LaTeX-Workshop#1020]
Right now there is no way to open more than one pdf viewer tab. I would like to split the tab to see different pages of the same pdf document at the same time.

Thanks!

**Comment by James-Yu** [comment]
Actually you can now. Click the split pane button for the effect.

**Comment by edgardozoppi** [comment]
I cannot make it work for me. I right-click on the pdf viewer tab and select one of the split options of the context menu like Split Up, but the new tab (in this case above of the original one) is empty.

I think you should be able to reproduce this issue. I have the latest version of both VS Code and your extension.

**Comment by zoehneto** [comment]
@James-Yu I have the same problem when using the latex workshop viewer in the browser. Currently the root file is used as the key for the registered clients so even if i create a second viewer in the browser (by duplicating the tab of an existing viewer) this will register the viewer and since it shows the same file the websocket is overwritten. So now I have a second viewer but the first one doesn't get notified about changes.

Apart from that it is also impossible to launch more than one viewer per root file, since latex workshop checks if there is already a client registered and then just refreshes that client.
