### ISSUE TITLE
[Feature Request] Podman support

### ISSUE THREAD

**Issue by AdrianKoshka** [James-Yu/LaTeX-Workshop#1130]
**Is your feature request related to a problem? Please describe.**
My FR isn't related to any problem.

**Describe the solution you'd like**
There already is `docker` support, I'd like there to be [`podman`](https://podman.io/) support. I'd prefer to use `podman` over `docker` because `podman` can be used to create rootless containers, and doesn't require extra privileges like `docker` does. Perhaps this could be done via a configuration option that let's you choose whether to use `docker` or `podman`.

**Describe alternatives you've considered**
I haven't considered any.

**Additional context**

`podman` github page: https://github.com/containers/libpod

**Comment by James-Yu** [comment]
Unfortunately, before the referenced software became an industry-standard-like-thing, there is no plan to implement such supports from my side. PRs always welcomed.

Note that even docker only gets experimental support. I myself does not use it, and has no way to test the implementation. This is why #1069 is still open.

**Comment by AdrianKoshka** [comment]
Oh okay, `podman` is OCI compatible and docker compatible fwiw. So it's more or less a drop-in replacement. Understandable though.

**Comment by ebousse** [comment]
Sorry to post while the issue is marked as closed, but I simply wanted to mention that possibly one simple way to solve this would be to add a configuration option in latex-workshop to allow users to choose the path to the used docker binary. This would make it possible to point to `podman` instead, which as @AdrianKoshka mentionned is a drop-in replacement in the simpler cases (such as this one).
