### ISSUE TITLE
Custom class -load command suggestions

### ISSUE THREAD

**Issue by tecosaur** [James-Yu/LaTeX-Workshop#1178]
I have ended up highly customising my latex template, to reduce the per-document text overhead  I've externalised this into a custom class that loads ~40 packages.

The issue I have is that now when using a document that makes use of this class (i.e. all of my documents), since the extension doesn't see any package loading lines I don't get any of the corresponding snippets.

What would be the best way to try to resolve this issue?
Currently, my best thought is adding a setting to specify the location of custom class files so that they may be parsed.

**Comment by jlelong** [comment]
We do not parse classes, nor packages and won't be doing so. It is far too complicated.

Currently, the commands provided by a package are defined in [data/packages](https://github.com/James-Yu/LaTeX-Workshop/tree/master/data/packages). These data are extracted from [LaTeX-cwl](https://github.com/LaTeXing/LaTeX-cwl). 

For your problem, I guess the best solution would be to put everything in a macro file instead of a class and use `\input`. Then, we would only need a setting to tell LW where to find extra files, for instance `latex-workshop.latex.texDirs`. I will add this feature today.

**Comment by tecosaur** [comment]
That sounds like a good idea. In my case, the only problem is that my class has grown to ~1.2k lines with ~15 options that affect package loading and setup.

Would you have any ideas on how I, and others in my situation (admittedly probably not _that_ many people, but still...) would be able to resolve this?

At the moment I have two thoughts.
 1. Rudementry parsing of `.cls` files - Just getting all instances of `\RequirePackage`
 2. The user entering what packages should be assumed to be loaded when class `xyz` is used

**Comment by jlelong** [comment]
A long time ago, I was also using a workflow with a personal class but I stopped at some point because it had become too difficult to submit papers to journals or open archives.

Anyway for your problem, I think it is not reasonable to start parsing package files and classes, because we will end up parsing far too many files and we may even end up in infinite loops as we will never be able to correctly go through the different `\if` sections. 

Then, your second solution to provide a list of packages to load whatever `\usepackage` you use sounds better. I even think (see [there](https://texfaq.org/FAQ-optionclash)) that you could just create a file `xxxx.tex` with all the `\usepackage` without any option and just use `\input{xxx.tex}`.

**Comment by tecosaur** [comment]
Thank you for your insight regarding usage of a personal class. That was something I hadn't really considered before. I'll bear that in mind.

Regarding parsing, what I was thinking was really basic, just regex searching for all `\newcommand` instances etc.

On the side of `\input{xxx.tex}` that definitely sounds like a better idea than what I was thinking previously. For a more global solution that won't require copying that file across for every new .tex file I produce - do you think it would be possible to create some sort of global association based on class?
Something like this
```json
config.json
...
"latex-workshop.class-associations": [
    {
         "className": "customclass",
         "packageIncludesFile": ".../.../customclass/packageLoading.tex"
    }
]
```

**Comment by jlelong** [comment]
The purpose of the new configuration variable `latex-workshop.latex.texDirs` I am about to add is precisely to search for inputed files elsewhere than in the current project directory. With this new setting, you won't need to copy your `xxx.tex` in each project but only to add the `\input{xxx.tex}` in your root file. I think this will provide the feature you are asking for without introducing too much development.

**Comment by tecosaur** [comment]
One last thing, do you know of any way that I can have a `\input{xxx.tex}` line that is parsed by LaTeX workshop, but not actually read by the latex compiler?

It would be much better if for each line such as `\newcommand{\R}[1][]{\ensuremath{\ifstrempty{#1}{\mathbb{R}}{\mathbb{R}^{#1}}}}` in my `.cls` file, all I need in the `xxx.tex` file to provide intellisense is `\newcommand{\R}{}`, as it would both simplify the file, and make it so that I don't have to remember to copy past every changed to a defined command.

**Comment by jlelong** [comment]
Just enclose the content of `xxxx.tex` with `\if10...\fi`
```
\if10
all the content you need for intellisense
\fi
```
or put the `\if10...\fi` around the `\input{xxx.tex}` instruction.

Just to make it clear `\if10` tests if `0` is `1` which is always false.

**Comment by tecosaur** [comment]
Thanks jlelong! You're quite helpful :smiley:
