### ISSUE TITLE
latex-workshop.latex.external.build.command does not override default

### ISSUE THREAD

**Issue by dschuessler** [James-Yu/LaTeX-Workshop#1276]
Thanks for your awesome work. I am trying to set up Latex-workshop for use with the [tectonic](https://github.com/tectonic-typesetting/tectonic) typesetting system like this:

```JSON
"latex-workshop.latex.external.build.command": {
  "command": "tectonic",
  "args": [
    "%DOC%"
  ]
}
```

Documentation says the following.

> The external command to execute when calling latex-workshop.build. [...] When defined, it completely bypasses the recipes and root file detection mechanism

Nonetheless Latex-workshop invokes pdflatex on file save.

I have no other Latex-workshop-specific settings in my settings.json. Tectonic is in my path and can be successfully invoked from the command line. I'm using Visual Studio Code 1.32.2.

On a side note I'm irritated by the use of the `%DOC%` alias. Does it include the file ending? Is it even necessary to pass it as an argument? Any help would be greatly appreciated.

**Comment by jlelong** [comment]
It think it has just been fixed by d2a115e. It will be included in the next release.

From the wiki

| Placeholder | Replaced by                                                                                        |
| ----------- | ----------------------------- ----------------------------------- |
| `%DOC%`     | The LaTeX root file path and name without the `.tex` extension  |
| `%DOCFILE%` | The LaTeX root file name without the `.tex` extension               |
| `%DIR%`     | The LaTeX root file path
