### ISSUE TITLE
Bug in (xe)(la)Tex keyword highlither(parser), evaluates (xe)(la)tex comands in macros definition

### ISSUE THREAD

**Issue by 07pepa** [James-Yu/LaTeX-Workshop#1381]
BUG:
Highliter evaluates certain comands in macros

How to replicate bug

make latex  document  and before  
```latex
\begin{document}
``` 

define macro with \def  like 
```latex
\def\mycomand{\begin{lstlisting}}
```

highlither things that \begin{lstlisting} in macro actualy starts listing ( works with verbatim too) and don't  continues with highliting

hotfix (and proof that this is what highliter is actualy dooing) is to put 
```latex
%\end{lstlisting} // or verbatim
```
after macro that ends block in parsers head and it start highlithing again

**Comment by jlelong** [comment]
Unfortunately we cannot do much about it as the highlighter only parses the content line by line and there is no way backward.

**Comment by 07pepa** [comment]
@jlelong 
well even if macro is on same line as begining of listing it still messes up... 

at least then you could detect that comand is in macro and not understand it as comand ( no trips to past needed)

also your higlither remember things in past like i am in verbatim block or in listing block and not highlight any comand... so there has to be a way to do it  for macro on multiple lines


for multiple lines fix would be:
 that if your encounter makro you set flag "i am in macro"  and you would not unset it unlil you leave macro  ....you can detect then if you are in macro and don't evaluate begins of verbatim or listing


i have feeling that this has been closed prematurely and request aditional rewiew by @James-Yu

**Comment by jlelong** [comment]
I will try to make my point clearer.

- To detect if we are inside a macro definition, we would need to match braces pairs, which we do not because it creates too many problems. We actually stopped matching `{....}` groups in c10ca0c. There are a few exceptions to this but macro definitions are far too complicated to make an exception.
- Highlighting works the following way for `verbatim` environments: when `\begin{verbatim}` is encountered, everything coming next is marked as `verbatim` until `\end{verbatim}` is encountered. There is no way to revert this decision if no `\end{verbatim}` is ever encountered.

As you can see, you probably feel wrong. You should have at the grammar definition and you will that your flag idea is not implementable. Anyway if you think you have a better idea, PR is always welcome.

**Comment by 07pepa** [comment]
@jlelong  understood
