### ISSUE TITLE
Some quirks detecting inline and display math environments for preview

### ISSUE THREAD

**Issue by memeplex** [James-Yu/LaTeX-Workshop#1393]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Describe the bug [Required]**

Maybe this is so by design, but in display style math I only get the mathjax preview when hovering over the initial `\[` which is sometimes hard to hit, specially with a trackpad. Hovering over any place in inline math `$...$` or `\(...\)` opens the preview, instead.  

**To Reproduce**

1. Enter some multiline math display environment (surrounded by `\[` and `\]`)
2. Put mouse over initial `\[`: a preview opens.
3. Put mouse anywhere in the math environment but the opening `\[`: preview doesn't pop up.

**Expected behavior**

Preview opens hovering everywhere in the `\[...\]` environment. Or at least in an easier to hit portion of it (`\[` is too small!).

**Logs [Required]**

I don't see any relevant log.

**Desktop [Required]:**

- OS: Arch Linux
- VS Code version: 1.34.0
- Extension version: 7.0.0

**Comment by memeplex** [comment]
I'm seeing this also happens for inline math with `\(...\)` delimiters. For `$...$` delimiters with multiline content, the preview is not even launched. Otherwise, `$...$` in a single line raises the preview by hovering anywhere, as one would expect.

**Comment by memeplex** [comment]
To sum up:

1. Multiline expressions `\(...\)`, `\[...\]`, `\begin{align}...\end{align}` etc should ideally show a preview while hovering on any part of them. If this is not possible or desirable, at least increment the prefix for `\(` and `\[` because it's difficult to quickly hover them.

2. `$...$` should be recognized across newlines.

**Comment by jlelong** [comment]
A few explanations on previewing and hovering

1. We restrict `$...$` to be on a single to avoid too many interferences with `$$...$$`. See the discussions in #1284. This will not be changed
1. We intentionally do not trigger preview when hovering outside the begin pattern (ie `\[`, `\begin{...}`, `$$`) because hovering may be used to to provide other features than preview, see the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/Hover#documentation-of-a-command). Moreover, you certainly do not want preview to pop up any time you move the mouse inside a math environment
1. `\(...\)` is indeed recognized for preview both in single and multi line constructions but there is a difference
    - in single line constructions, preview is triggered at any position inside the expression
    - in multi line constructions, preview is only triggered when on `\(`.

Extending a bit the triggering patterns for `\(`, `$$` and `\[` would require to redesign most of the localization mechanism and this is beyond the man power we have and this is not clear how much to extend it.

**Comment by memeplex** [comment]
Wrt 1, it's reassuring to see you have thought so much about this and it was not just neglected. I see your rationale. But, still, it's too common to have very short expressions like `log x` for which `\(....\)` may be too noisy a pair of delimiters and that could be separated in two lines by the formatter. Would you consider taking into account an entire paragraph instead of a single line? It doesn't seem to change the nature of the regex too much nor to be of concern regarding performance of the parser.

Wrt `Extending a bit the triggering patterns for \(, $$ and \[` why is that hard? Is this using the same syntax parser than the colorizer? Couldn't a lookahead be used?

**Comment by memeplex** [comment]
2 also reinforces my first point above. Is all too common to use a couple of spaces in short inline expressions. I would say most inline expressions contain at least one space but, at the same time, most of them don't expand more than two lines. Now, having to use `\(...\)` not only is noisy for very short expressions as I pointed out before but also is in detriment of the preview detection mechanism that, because of a change from `$` to `\(`, suddenly requires to carefully position the hover. And, in advance, it would be a good practice to use only `\(` except for the simplest expressions, so the hover mechanism will degrade. Plus having to decide which delimiter to use for each case is cognitive burden, just like having to consume a mix of delimiters afterwards.  Extending the parser to consider a paragraph instead of a single line resolves most practical  ambiguities with `$`.

**Comment by jlelong** [comment]
> Wrt Extending a bit the triggering patterns for `\(`, `$$` and `\[` why is that hard? Is this using the same syntax parser than the colorizer? Couldn't a lookahead be used?

No the syntax parser is an internal VSCode mechanism described by an xml file of rules. 

I have the feeling that you use hard line wrapping (probably relying on an extension) rather than using the built-in soft wrapping provided by VSCode and this is why you would like to extend the parser to consider a paragraph instead of a single line.

**Comment by memeplex** [comment]
Indeed I use hard wrapping, I would like to avoid that but I write a lot of math and most of the documents end up being more like carefully indented code than easily flowing text. For simple markdown documents I do use soft wrapping.

**Comment by memeplex** [comment]
So @jlelong do you think it's a reasonable request to extend the parsed region to an entire paragraph in order to allow for some short multiline math fragments? I see the advantages of soft-wrapping, don't think I have not tried to move to pure soft-wrapping writing from time to time, but many people writing LaTeX still expect you to hard wrap at column 80 or so and use Vim or Emacs which are crappy doing soft-wrapping but the best ones at hard-wrapping. Also list environments are IMO better formatted by manually intending continuation lines after the opening `\item` line. If you are reluctant to introduce that modification yourself I might write a patch in a couple of weeks, I'm still in the vscode inception phase, so to speak. And vscode is not written in elisp, so I must acquire some abilities first.

**Comment by jlelong** [comment]
As you explained, `$...$` is often only used for very short expressions for which preview does not prove so useful. Moreover, the reason to consider a whole paragraph (ie lines delimited by blank lines?) is only to handle hard wrapped text because for soft wrapped text, we already handle paragraph, as in this context a paragraph lies on a single line. 

For this reason, I am sorry to say that I do not think the extension to an entire paragraph is worth it especially considering that we limit amount of spare time to work on the extension. Of course, any reasonable PR on this is welcome.

**Comment by memeplex** [comment]
Ok, thank you very much for taking the time to explain.
