### ISSUE TITLE
Does the executable exist? PATH: /usr/bin:/bin:/usr/sbin:/sbin

### ISSUE THREAD

**Issue by kenshohara** [James-Yu/LaTeX-Workshop#1414]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.**

**Describe the bug [Required]**

**To Reproduce**
1. Create a test directory that includes test.tex.
test.tex is ```\documentclass[10pt,twocolumn,letterpaper]{article}\begin{document}test.\end{document}```

2. Executing "Build with recipe"
My settings.json is the following.
```
"latex-workshop.latex.recipes": [
        {
            "name": "pdflatex",
            "tools": [
                "latexmk_pdflatex"
            ]
        }
    ],
    "latex-workshop.latex.tools": [
        {
            "name": "latexmk_pdflatex",
            "command": "latexmk",
            "args": [
                "-pdf",
                "%DOC%"
            ]
        }
    ]
```
3. See error
```
[13:55:39] Recipe step 1: latexmk, -pdf,path/to/test/test
[13:55:39] LaTeX build process spawned. PID: undefined.
[13:55:39] LaTeX fatal error: spawn latexmk ENOENT, . PID: undefined.
[13:55:39] Does the executable exist? PATH: /usr/bin:/bin:/usr/sbin:/sbin
```
**Expected behavior**
PATH should includes /Library/TeX/texbin,
because my $PATH is the following.
```
> echo $PATH
/usr/local/bin /usr/bin /bin /usr/sbin /sbin /Library/TeX/texbin
```
My login shell is fish. But $PATH in /bin/bash and /bin/sh also include /Library/TeX/texbin.
When I execute latexmk in any shell in my terminal and integrated terminal of VS Code, latexmk worked correctly.

**Logs [Required]**
```
[13:48:39] Initializing LaTeX Workshop.
[13:48:39] Cannot run pdflatex to determine if we are using MiKTeX
[13:48:39] Creating LaTeX Workshop http and websocket server.
[13:48:39] LaTeX Workshop initialized.
...
[13:55:39] Recipe step 1: latexmk, -pdf,path/to/test/test
[13:55:39] LaTeX build process spawned. PID: undefined.
[13:55:39] LaTeX fatal error: spawn latexmk ENOENT, . PID: undefined.
[13:55:39] Does the executable exist? PATH: /usr/bin:/bin:/usr/sbin:/sbin
```

**Desktop [Required]:**
 - OS: Mac OS Mojave
 - VS Code version: 1.34.0
 - Extension version: 7.0.0

**Comment by tamuratak** [comment]
Please clarify that how you start VS Code. On Finder or Terminal?

Make sure how ` /Library/TeX/texbin` is appended into `$PATH` in your mac. On my mac (macOS High Sierra), `/etc/paths.d/TeX` is loaded. See `man path_helper`.

**Comment by kenshohara** [comment]
I started VS code on Finder.
I confirmed that ```/Library/TeX/texbin``` is appended into $PATH again by using ```echo $PATH```.
My ```/etc/paths.d/TeX```  is also ```/Library/TeX/texbin```.

**Comment by tamuratak** [comment]
I think this issue is not related to LaTeX Workshop. Your configuration is not appropriate.

When I start VS Code from Finder on my mac, the error message of LaTeX Workshop is the following.
```
[19:36:56] LaTeX fatal error: spawn pplatex ENOENT, . PID: undefined.
[19:36:56] Does the executable exist? PATH: /Users/tamura/.rbenv/shims:/Users/tamura/.cargo/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Library/TeX/texbin:/opt/X11/bin:/Users/tamura/bin:/Users/tamura/Library/Python/3.6/bin:/opt/local/bin:/opt/local/sbin/
```

The paths, `/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Library/TeX/texbin:/opt/X11/bin`, are loaded from `/etc/paths` and files in `/etc/paths.d/`. The other paths are set in my configuration files under my home directory.

LaTeX Workshop never touch `$PATH`. So, if your configuration is appropriate, `$PATH` should include `/Library/TeX/texbin`.

**Comment by tamuratak** [comment]
A possible workaround is starting VS Code from Terminal where `$PATH` is set appropriately.

**Comment by kenshohara** [comment]
You are right. When I executed VS Code on not Finder but Terminal, I could correctly built my tex file.
In my ```PATH```, ```/Library/TeX/texbin``` is loaded from ```/etc/paths.d/TeX``` but VS Code from Finder does not include ```/Library/TeX/texbin``` in ```PATH```.
Do you have any ideas about this?
But I know this is not related to this extension.
If @tamuratak do not have any ideas, I close this issue.

**Comment by tamuratak** [comment]
No. I do not know much about `fish`. 

`/etc/profile` calls 
```
eval `/usr/libexec/path_helper -s`
```
The command `path_helper` with  the argument `-s` prints `PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Library/TeX/texbin"; export PATH;` which is for variants of Bourne shell. `fish` is not a variant of Bourne shell. So, things do not work. I guess.

**Comment by kenshohara** [comment]
Thank you for answering.
I'm not sure this issue is specified to the fish shell because when I changed my login shell from fish to bash, this issue was not solved.
Anyway, thank you for your replies!

**Comment by mlettau** [comment]
I have the exact same problem on my Mac (latest versions of VSC and TexLive).  I have tried various shells (sh, bash, fish), so this issue is not related to any particular shell.  Recipes and tools in settings.json are standard.  My shell environment is also standard:

/etc/paths:
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin

/etc/profile:
# System-wide .profile for sh(1)
if [ -x /usr/libexec/path_helper ]; then
	eval `/usr/libexec/path_helper -s`
fi

/etc/paths.d includes file Tex withonly line
/Library/TeX/texbin

Shell-specific configuration files (.bashrc, bash_profile) with additional paths.

VSC settings.json includes
"terminal.integrated.shell.osx": "/usr/local/bin/bash",

Opening internal Terminal:  Path includes /Library/TeX/texbin, compiling via latex, pdflatex, ... works

Starting VSC from command line via code: Compiling using recipes works.

Starting VSC in Finder: Error when compiling via any recipe
[13:45:52] LaTeX build process spawned. PID: undefined.
[13:45:52] LaTeX fatal error: spawn xelatex ENOENT, . PID: undefined.
[13:45:52] Does the executable exist? PATH: /usr/bin:/bin:/usr/sbin:/sbin

Problem: Latex Workshop recipe path does not seem to invoke /usr/libexec/path_helper and read paths in /etc/paths.d  when started from Finder.

I have seen many users have the same issue but not found any solution that works (aside from starting VSC from command line).
