### ISSUE TITLE
Customizable shortcut for Backward/Reverse synctex (pdf to source)

### ISSUE THREAD

**Issue by ataiya** [James-Yu/LaTeX-Workshop#1464]
In the documentation I read:
```
Backward/Reverse synctex (pdf to source) is activated by ctrl + left-clicking (cmd + left-clicking on Mac) on the relevant element of the pdf preview.
```

However, other popular latex editors (e.g. overleaf) enable synctex by a simple double-click on the PDF. It would be good if the extension would allow for the shortcut to be used for this operation to be customized?

**Comment by trevorgunn** [comment]
The shortcut exists in the viewer webpage which is a stand-alone web-document that you could view in any web browser. As such, it exists outside of the VSCode API so it is not as straightforward to access user settings in the viewer.

The shortcut is hardcoded here: https://github.com/James-Yu/LaTeX-Workshop/blob/aeaa583f2c118cbe0c6cd112ef0ee7c85e675616/viewer/latexworkshop.js#L249-L252 and you can patch it to have the shortcut you want easily enough by changing `onclick` to `ondblclick` and removing the `if` block. Here's a diff that you can use to patch:

```diff
 249,253c249
<     canvas_dom.onclick = (e) => {
<         if (!(e.ctrlKey || e.metaKey)) {
<           return
<         }
< 
---
>     canvas_dom.ondblclick = (e) => {
```

One reason why ctrl-click is preferred is because double-clicking will select text. (Overleaf deals with this by unselecting the text after synctex.)

**Comment by ataiya** [comment]
Gotcha! Too bad the *.js cannot be parameterized to receive a shortcut spec on load.
Thanks for the patch!
