### ISSUE TITLE
Zotero integration

### ISSUE THREAD

**Issue by janosh** [James-Yu/LaTeX-Workshop#1547]
There's already a feature request for Mendeley integration (#153) in which Zotero is mentioned a couple of times.

This issue is basically it's sibling trying to get the ball rolling specifically for Zotero API support as well. The ideal workflow here would be that just by adding a reference to my Zotero library, it becomes available for selection in LaTeX Workshop without any intermediate steps syncing or updating steps on my part.

**Comment by tecosaur** [comment]
This is related to https://github.com/bnavetta/vscode-zotero-latex/issues/3

**Comment by tecosaur** [comment]
@James-Yu LW or LU?

**Comment by James-Yu** [comment]
I'd say LU 😄

**Comment by tecosaur** [comment]
You just want to push all the hard work onto someone else don't you! :stuck_out_tongue_winking_eye:

**Comment by tecosaur** [comment]
@janosh please reopen this issue in https://github.com/tecosaur/LaTeX-Utilities/.

@James-Yu is there a way I'd be able to label and close issues? While you (plural: you+tam+jleong) all seem perfectly compentent at it, it would be convienent if I was able to help with that as well, particularly since I don't plan on going anywhere soon.

**Comment by janosh** [comment]
@tecosaur Just created [this issue in LaTeX-Utilities](https://github.com/tecosaur/LaTeX-Utilities/issues/4). Thanks for the quick response!
