### ISSUE TITLE
Master mode

### ISSUE THREAD

**Issue by qi55wyqu** [James-Yu/LaTeX-Workshop#1598]
It would be great to have the same feature as **Texmaker's "Define current document as 'Master Document'"** so I can edit any file and compile the PDF when running build.

For example when I edit a LaTeX .cls or .sty file I cannot build my sample document but have to switch to the .tex file first. 

Or it would be useful if LaTeX-Workshop could just remember the last document I built and then run "Build LaTeX project" with the last document.

**Comment by uninyhart** [comment]
I think Master Mode is really useful.

It can solve #766 (plainTeX compatibility).

And here are some other applications I come up with:

1. If you want to make two (or more) PDF versions in one project (like trying some different styles), and some of the files are shared (Because latexworkshop finds `\begin{document}` to locate the root file and now you have two root files.)
2. Working with a large project, set up two root files: `main.tex` `chapter-preivew.tex`, and you can just write some sample codes in `chapter-preivew.tex` to accelarate compiling. (Of course you can create a Git Branch `dev` to fullfil it, but this is another way, and you don't need to merge the `main` file.)

**Comment by jlelong** [comment]
I do not understand why you cannot use the magic comment `!TEX root`, see the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/Multi-File-Projects).
