### ISSUE TITLE
Autocompletion with \ref stops at underscores

### ISSUE THREAD

**Issue by coxackie** [James-Yu/LaTeX-Workshop#1613]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**
You still see this issue?: Yes

**Describe the bug [Required]**
The auto-completion feature after typing "\ref" gives a list of labels, but the labels are cut at the first underscore; for example, "sec:first_try" becomes "sec:first".

**To Reproduce**
Just label something with an underscore, and then try to refer to it using "\ref{}"

**Expected behavior**
The auto-completion feature should give the whole label, not cut at the first underscore. This is what was happening with previous version (7.x)

**Desktop [Required]:**
 - OS: Linux (Arch)
 - VS Code version: 1.37.1
 - Extension version: 8.0.3

**Are you using LaTeX Workshop with VS Code Remote?**
No

**Comment by werunom** [comment]
I also have observed this issue. 

To mention another related issue, consider that there are labels: `Analysis_1`, `Analysis_2`, `Discussion_1`, `Discussion_2` and `Conclusion`

In this scenario, the intellisense gives only the following suggestions: `Analysis`, `Discussion` and `Conclusion`. (Since post underscore strings are not recognised, the duplicates are being removed.)

**Comment by James-Yu** [comment]
@tamuratak I believe this is a PEG problem.
