### ISSUE TITLE
Please don't match \rightarrow

### ISSUE THREAD

**Issue by tylerliu1998** [James-Yu/LaTeX-Workshop#1641]
Please don't match \rightarrow.
![bad](https://user-images.githubusercontent.com/48684632/63702742-8db6e780-c7f5-11e9-8425-7e345bb2bd4b.jpg)

**Comment by jlelong** [comment]
I cannot reproduce your screenshot. Are you using bracket colorizer or any other extension performing some pair matching?

**Comment by jlelong** [comment]
Note that Bracket Pair Colorizer 2 is reported to be incompatible with LW, see [here](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#known-incompatible-extensions). That being said, the issue mostly arises because `\left` and `\right` are declared as a pair, see [syntax/syntax.json#L5](https://github.com/James-Yu/LaTeX-Workshop/blob/c48365a3de08a4faa9b2ea99eba2e4cd8125cfd5/syntax/syntax.json#L5). See the discussions in #1529 and #1534.
