### ISSUE TITLE
Snippet support  for algorithm pseudo code packages

### ISSUE THREAD

**Issue by tylerliu1998** [James-Yu/LaTeX-Workshop#1717]
Hello,

Really enjoyed this extension. I wonder if there could be some snippets for pseudo code packages.

For example, when I type 'BAG', I hope it can generate algorithm environment with captions and an inner algorithmic environment. Similar to the itemize environment, we hope \State would automatically appear after creating a new line. Also when typing some blocks, we hope there could be an automatic {} matching the definition of the command and matched closing, for example,  when you type \For, {} appears to let you write the controlling sentence and \EndFor appears downward.

**Comment by jlelong** [comment]
You can define the `BAG` snippet yourself independently of the extension. As far as handling the `\State` keyword and others matching I am afraid this is far beyond the scope of this extension. Doing so would require a lot of extra code and because the LaTeX syntax is often awkward, in particular inside algorithm, it would be very difficult to make all this robust.
