### ISSUE TITLE
how to customize snippets

### ISSUE THREAD

**Issue by NeoFantom** [James-Yu/LaTeX-Workshop#1774]
If some of LaTeX-Workshop's snippets are not handy for me, how can I change them? 
E.g. currently `__` will trigger `_{$1}`, but instead I want to use `d` to trigger it.

**Comment by jlelong** [comment]
1. See [vscode's documentation] on how users can define their own snippets.
1. If you want to override the action associated to an existing prefix, use the configuration variable [latex-workshop.intellisense.commandsJSON.replace](https://github.com/James-Yu/LaTeX-Workshop/wiki/Intellisense#latex-workshopintellisensecommandsJSONreplace)

**Comment by trevorgunn** [comment]
I would add:

1. `latex-workshop.intellisense.commandsJSON.replace` isn't released yet. Also it only applies to snippets in `data/commands.json` whereas `__` is defined in `snippets/latex.json`. But this is fine since you can avoid the `__` snippet by simply not typing two `_`s.
2. You might be interested in the live snippets feature of [LaTeX-Utilities](https://github.com/tecosaur/LaTeX-Utilities) depending on your exact needs. The key differences are 1. live snippets don't require tab completion unlike regular snippets 2. they can make use of regex rules 3. they are context-aware (i.e. math mode vs text mode)
