### ISSUE TITLE
latex-workshop.latex.watch.files.ignore not fully honored

### ISSUE THREAD

**Issue by jlelong** [James-Yu/LaTeX-Workshop#1890]
This is related to https://github.com/James-Yu/LaTeX-Workshop/issues/1887#issuecomment-570956045

The configuration variable `latex-workshop.latex.watch.files.ignore` is only used when parsing the `.fls`  file but does not prevent an included file from being watched.

https://github.com/James-Yu/LaTeX-Workshop/blob/2a1cc913e2b67e89b0c2ff9c62346d5fb403ab2e/src/components/manager.ts#L333-L339

**Comment by jlelong** [comment]
Here is what I am about to implement. Any file matching `latex-workshop.latex.watch.files.ignore` will be completely ignored meaning that:
- it won't be parsed. In particular, its content won't be used in intellisense.
- it won't be watched.
Any comment on this choice?

**Comment by alexreg** [comment]
@jlelong Hmm, I'm not sure about the intellisense point. For example, what if I have a `preamble.tex` that I include in some document TeX files? I don't want build to run on `preamble.tex` itself, so I don't want it to be watched in that sense. (However, if I can watch e.g. `foo.tex` because it contains `\input{preamble.tex}`, and rebuild `foo.tex` when `preamble.tex` changes, this would be ideal.)

**Comment by jlelong** [comment]
If you leave `latex-workshop.latex.watch.files.ignore` to its default value and have `latex-workshop.latex.autoBuild.run: onFileChange`, `foo.tex` will be rebuilt every time `preamble.tex` changes, which seems to be exactly what you would like. If you are not familiar with the root file mechanism, you should read https://github.com/James-Yu/LaTeX-Workshop/wiki/Multi-File-Projects

In your example, the `rootFile` is `foo.tex`, so any change in any input/included file triggers a new build of `foo.tex`.
