### ISSUE TITLE
Autocompletion for control sequence containing @

### ISSUE THREAD

**Issue by joulev** [James-Yu/LaTeX-Workshop#1915]
**Is your feature request related to a problem? Please describe.**
When writing a package file, one has to deal with a lot of commands (control sequences) containing the "at" character `@`, e.g. `\hello@world`. While "normal", "user-level" commands are recognized and can be auto-completed later, these `@`-commands are not recognized. They are usually long, so auto-completion is necessary.

**Describe the solution you'd like**
Commands like `\hello@world` being treated the same way `\helloworld` is being treated.

**Describe alternatives you've considered**
Well, there are none.

**Additional context**
Please tell me if there is anything unclear.

**Comment by tamuratak** [comment]
Out of the scope of this extension.

**Comment by jlelong** [comment]
It should have already been working but there was a bug, fixed in 86c894b.

With  your example, if `\hello@world` is defined as a `\def\hello@world` or used somewhere in the file, trying to complete `\hello` will list `\hello@world`. However, as `@` is considered as a word delimiter, `\hello@` will not offer any good completion. It is not possible to change this without breaking lots of other things.
