### ISSUE TITLE
LaTeX toolchain terminated with error

### ISSUE THREAD

**Issue by nfode** [James-Yu/LaTeX-Workshop#192]
### Description

Building a .tex file does not work. latexmk and texlive is properly installed.

### How to reproduce

1. Open a .tex file
2. Press ctrl+shift+p
3. Search for *Build LaTeX project* and hit enter.

### Expected behavior

Correct PDF is created. 
### Actual behavior

In the .tex file folder `filename.fdb_latexmk` and `filename.aux` are generated.
`filename.fdb_latexmk` contains:
```
# Fdb version 3
["pdflatex"] 1499886694 "/home/nfode/test/test.tex" "test.pdf" "test" 1499886694
  "/home/nfode/test/test.tex" 1499886430 2444 f714e27fca8b549e8ee059a2ea1aa60f ""
  "test.aux" 1499886441 8 a94a2480d3289e625eea47cd1b285758 ""
  (generated)
  "test.log"
  "test.pdf"
```

`filename.aux` contains:
```
\relax 

```

And there is the error: **LaTeX toolchain terminated with error** in the statusbar.

### LaTeX Workshop log messages

<details>
<summary>Log messages</summary>

</details>
There are no log messages.

**Comment by James-Yu** [comment]
Please provide the extension log messages. The `.log` file content is also appreciated.

**Comment by DFelten** [comment]
I've got the same error since the latest update of LaTeX-Workshop. Exactly the same document has worked before. It seems to hang with the .lol file, since this can not be deleted (Except the pdflatex process is terminated).

The .lol file is 

This is the current log file
[Ausarbeitung.zip](https://github.com/James-Yu/LaTeX-Workshop/files/1145590/Ausarbeitung.zip)

**Comment by nfode** [comment]
@James-Yu there is no log file.

**Comment by James-Yu** [comment]
@nfode I mean the log messages of the extension. You can access from the `output` panel of vscode.

**Comment by nfode** [comment]
Ah sorry. Here you go!
```[17:58:33] Found root file from active editor: /home/nfode/Nextcloud/uni/4.Semester/Modellierung/modellierung2017/Blatt 9/abgabe.tex
[17:58:33] Root file remains unchanged from: /home/nfode/Nextcloud/uni/4.Semester/Modellierung/modellierung2017/Blatt 9/abgabe.tex.
[17:58:35] BUILD command invoked.
[17:58:35] Found root file from active editor: /home/nfode/Nextcloud/uni/4.Semester/Modellierung/modellierung2017/Blatt 9/abgabe.tex
[17:58:35] Root file remains unchanged from: /home/nfode/Nextcloud/uni/4.Semester/Modellierung/modellierung2017/Blatt 9/abgabe.tex.
[17:58:35] Building root file: /home/nfode/Nextcloud/uni/4.Semester/Modellierung/modellierung2017/Blatt 9/abgabe.tex
[17:58:35] Build root file /home/nfode/Nextcloud/uni/4.Semester/Modellierung/modellierung2017/Blatt 9/abgabe.tex
[17:58:35] Toolchain step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,/home/nfode/Nextcloud/uni/4.Semester/Modellierung/modellierung2017/Blatt 9/abgabe.tex
[17:58:35] LaTeX fatal error: spawn latexmk ENOENT, . Does the executable exist?
[17:58:38] Root file remains unchanged from: /home/nfode/Nextcloud/uni/4.Semester/Modellierung/modellierung2017/Blatt 9/abgabe.tex.
```

**Comment by James-Yu** [comment]
`[17:58:35] LaTeX fatal error: spawn latexmk ENOENT, . Does the executable exist?`

The extension cannot find `latexmk`, which should be in `PATH`. Otherwise, you need to specify its location.

**Comment by nfode** [comment]
Yeah my problem is: it is in the path and also works fine from the command line. But the LaTex Preview plug in also does not work because it can not find latexmk in the path. So it seems that this is a vscode problem.

**Comment by tvald** [comment]
I had to completely restart VS Code (quit all instances) before it was able to find `latexmk`.

**Comment by viasisco** [comment]
on my case the solution was to create a ~/.bash_profile with this line `export PATH="/usr/local/texlive/2017/bin/x86_64-darwin:$PATH"
` and to configure my default shell to bash.

**Comment by bianzhiyu** [comment]
I have the same problem.

**Comment by bianzhiyu** [comment]
when I call
`latexmk --version`
in the vscode terminal,
it returns 
`latexmk: The Perl interpreter could not be found.`
Will it be the reason?

**Comment by Stephen-X** [comment]
Hi everyone, I'm currently using LaTex Workshop on Windows. I encountered this error as well, and since the plugin itself doesn't produce more helpful error information, it took me a while before I figured out what went wrong and made everything work. In my case, the key is to check that `latexmk` (i.e. the default LaTex toolchain in Workshop's settings) is accessible and working from a command line window **without administrator permission**. On Windows, this means:

1. Install [Strawberry Perl](http://strawberryperl.com/) first.

2. Make sure you can read from & **write** to the root directory to your LaTex executables **without administrator permission**. `latexmk` will throw a "Windows API error 5: Access is denied" error if it can't write to its installed directory. You can resolve this by either installing LaTex to directories other than Program Files / ProgramData etc., or allow full control to the User group in Folder Properties > Security tab > Edit button > Users (XXX\Users).

**Comment by ClementAubry** [comment]
Hi,I have a similar problem

The error is encountered when I open code with a `code -a ./` in a folder containing my tex files and then I try to compile one of the opened tex file by Ctrl+Alt+b.

If I double click on a tex file, code will open and Ctrl+Alt+b will work fine.

So the only way for me to open my folder is first to open a single Latex file and then open a folder from this instance of code.

My path and default shell are correctly configured with texlive 2016.
Conf :  Ubuntu 16.04.4 LTS, Code 1.22.1, Latex-workshop 5.1.0

**Comment by Highstars1** [comment]
> on my case the solution was to create a ~/.bash_profile with this line `export PATH="/usr/local/texlive/2017/bin/x86_64-darwin:$PATH" ` and to configure my default shell to bash.

This perfectly solved my problem. I somehow deleted this path while doing some operation in bash_profile. Thanks a lot!

**Comment by davydden** [comment]
> on my case the solution was to create a ~/.bash_profile with this line export PATH="/usr/local/texlive/2017/bin/x86_64-darwin:$PATH" and to configure my default shell to bash.

that does not solve the problem on my mac, neither does a complete restart of `VSCode`. It's very strange as it has been working fine just a few hours ago...

**Comment by ruipimentel** [comment]
I have just started receiving this error after upgrading VSCode to version 1.30.

I'm running Linux Mint 17.3.

**Comment by choeffer** [comment]
In my case, debian stretch, latexmk seems not to be installed by default when installing texlive and texlive-latex-extra package. So after installing https://packages.debian.org/stretch/latexmk it is working fine.
