### ISSUE TITLE
intellisense dynamically add environments after use

### ISSUE THREAD

**Issue by hanzckernel** [James-Yu/LaTeX-Workshop#1927]
As I read through the manual I noticed the following: 

> The files of a LaTeX project are searched for any already used commands in the form mycommand followed by several {} groups. Then, a snippet is dynamically built for each of them and they are added to the command completion list. ...Moreover, any custom environment is added to the list after being used once.

but upon save I did not see it happen:

![question](https://user-images.githubusercontent.com/43314240/73608549-da80c480-45c4-11ea-9555-f1d93ab9c0e2.png)

In my `env.sty` file I wrote something like:
```latex
\newtheorem{proposition}[theorem]{proposition}
```

Am I using the Intellisense the wrong way?

**Comment by jlelong** [comment]
First of all, we do not scan any packages because they are far too complicated. Standard packages provide a list of defined commands and environments but for user defined packages we cannot do anything. 
Because there are so many different ways to define an environment, we do not scan for environment definitions but instead we track the `\begin{...} \end{...}` calls and we automatically insert the already used environments to auto-completion for  the`\begin{...} ... \end{...}` snippet.

In your case, try typing `\beg` and complete to `\begin ... \end` then an intellisense popup should show up and list `proposition`.

**Comment by hanzckernel** [comment]
@jlelong  Thanks!! I tried to follow your instructions but still the intellisense does not show proposition in the list
![Screenshot from 2020-02-02 15-05-47](https://user-images.githubusercontent.com/43314240/73609441-e91fa980-45cd-11ea-9875-de891d780657.png)

On the other hand, the used new command are shown in intellisense suggestions.

Also is there any way to ask intellisense to scan some preamble `sty` file where all new commands are defined?

**Comment by jlelong** [comment]
You are right, there is a bug. I am on it.
