### ISSUE TITLE
The placeholder %OUTDIR% on Windows

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#2010]
@jlelong I ask you a question on the placeholder, `%OUTDIR%`, on Windows. In the current `master` branch, backward slashes are used in `%OUTDIR%` on Windows since [path.normalize](https://nodejs.org/api/path.html#path_path_normalize_path) replace forward slashes with backward slashes on Windows. Is this an intended behavior?

https://github.com/James-Yu/LaTeX-Workshop/blob/bce11da246b8ae8b12b2fa0ea43b230fd3113e91/src/components/manager.ts#L82

We can see the behavior of `path.normalize` on Windows by calling `path.win32.normalize` on other platforms.

```node
path.win32.normalize('C:////temp\\\\/\\/\\/foo/bar');
// Returns: 'C:\\temp\\foo\\bar'
```

Related to #1897, #1904, and #1947.

**Comment by jlelong** [comment]
I guess there is something here, the line should instead read

```
return path.normalize(out).split(path.sep).join('/')
```

We do want output paths to always use `/` even on Windows.

**Comment by tamuratak** [comment]
With the commit,  9ca0c06, `%OUTDIR%` cannot be used with `cmd.exe` in recipes on Windows as far as I tried. For example, the following recipe does not work. I do not have a specific opinion that it should work.

```js
{
    "latex-workshop.latex.recipes": [
        {
          "name": "latexmk_copy",
          "tools": ["latexmk", "copyPDF"]
        }
    ],
    "latex-workshop.latex.tools": [
        {
          "name": "latexmk",
          "command": "latexmk",
          "args": [
            "-synctex=1",
            "-interaction=nonstopmode",
            "-file-line-error",
            "-pdf",
            "-outdir=%OUTDIR%",
            "%DOC%"
          ],
          "env": {}
        },
        {
          "name": "copyPDF",
          "command": "cmd.exe",
          "args": ["/C", "copy", "\"%OUTDIR%/%DOCFILE%.pdf\"",  "\"%OUTDIR%/b.pdf\""],
          "env": {}
        }
    ]
}
```

**Comment by tamuratak** [comment]
We can try the recipe on GitHub Actions. See 
- https://github.com/James-Yu/LaTeX-Workshop/compare/master...tamuratak:d0569769c1a771a11e84f933eef39d00ba8b3605 
- https://github.com/James-Yu/LaTeX-Workshop/tree/d0569769c1a771a11e84f933eef39d00ba8b3605

**Comment by jlelong** [comment]
I missed that point. This is indeed an issue. Short summary

- some LaTeX compilers such as `lualatex` require the use of `/`. This can be achieved by setting `$MSWin_back_slash=0` in `latexmk`. Since `latexmk-4.69`, there is even a command line option for that `-MSWinBackSlash-`.
- When `%OUTDIR%` dir is `./`, we cannot use back slash as `.\` causes errors.
- The use of `\` breaks `cmd.exe`

It seems to me that `%DOC%`always uses `/``
https://github.com/James-Yu/LaTeX-Workshop/blob/933f095c1f1cb9ceeaeae6d98f077dad2b902f4e/src/components/builder.ts#L514-L529

So I would be tempted to do the same for `%OUTDIR%`.

**Comment by tamuratak** [comment]
As far as I tried, On the command prompt of Windows, the following works well with forward slashes:
```
cmd.exe /C copy "C:/path/a.pdf" "C:/path/b.pdf"
```

I do not know why the recipe does not work.

**Comment by tamuratak** [comment]
An easy solution is providing placeholders with backward slashes, `%OUTDIR_W32%`, `%DOC_W32%`, ... and placeholders with forward slashes, `%OUTDIR%`, `%DOC%`, ... at the same time on Windows.

**Comment by jlelong** [comment]
That's sure. It might be related to https://github.com/nodejs/node-v0.x-archive/issues/25895#issuecomment-180402332

**Comment by jlelong** [comment]
I think the explanation is https://github.com/nodejs/node/issues/5060#issuecomment-179472815
We need to pass `{windowsVerbatimArguments: true}` to prevent `node` from escaping all quotes.
See the corresponding test https://github.com/jlelong/LaTeX-Workshop/runs/545593932?check_suite_focus=true

All this is related to the way arguments to `cmd.exe` should be quoted. Using [`cross-spawn`](https://github.com/moxystudio/node-cross-spawn), we can make everything work by simply dropping `cmd.exe` and using `copy` as the command. If the `cmd` does not exist, `cross-spawn` automatically wraps up the command and its argument and pass the whole to `cmd.exe` with the appropriate escaping. See https://github.com/jlelong/LaTeX-Workshop/runs/545688242?check_suite_focus=true 

https://github.com/jlelong/LaTeX-Workshop/blob/c8a4d3ff79bc4e5ffb2db3630db58f10991742ad/test/fixtures/build/fixture100/.vscode/settings.json#L22-L27

https://github.com/jlelong/LaTeX-Workshop/blob/49f68155c4b658d9af2ac4ddb2451d9398529e88/src/components/builder.ts#L270

where `cs` is `cross-spawn`.

As a conclusion of all this, I would be tempted to use `cross-spawn` everywhere. We already use `cross-spawn` to run `latexindent` following #1873 because escaping issues with spaces.

**Comment by jlelong** [comment]
@tamuratak What do you think of this?

**Comment by tamuratak** [comment]
My main concern is that there might be a case `cmd.exe` does not work well with forward slashes. See https://stackoverflow.com/questions/10523708/why-does-the-cmd-exe-shell-on-windows-fail-with-paths-using-a-forward-slash
However, we can add `%OUTDIR_W32%`, `%DOC_W32%`, ..., later if users request them.

So, if `cross-spawn` works well with typical recipes other than default ones, I think it is definitely ok. We might need some more tests.

**Comment by tamuratak** [comment]
One example I am considering is a recipe using  a quote,`q/.../`, with `latexmk`. See https://texwiki.texjp.org/?Visual%20Studio%20Code%2FLaTeX#c465cb18. The use `/` in `q/.../` might be problematic.

**Comment by jlelong** [comment]
OK to `_W32` placeholders with backward slashes.

`cross-spawn` is just a wrapper around `child_process` so it should not hurt. I will make a new branch to test it intensively. Btw, many thanks to your test framework. It is awesome.

**Comment by tamuratak** [comment]
I have a question. Do users who are already using recipes with `cmd.exe` have to rewrite their recipes by dropping `cmd.exe`? Is there any other case that a user has to rewrite the recipe?

**Comment by jlelong** [comment]
The use of `q/.../` might be an issue. I will have a look at it using `cross-spawn`.

> Do users who are already using recipes with `cmd.exe` have to rewrite their recipes by dropping `cmd.exe`? Is there any other case that a user has to rewrite the recipe?

No I do not think so. My understanding is that everything that already works with `child_process` will still work with `cross-spawn`.  It is designed as a drop-in replacement. It only avoids resorting to tricky options or escaping.

**Comment by jlelong** [comment]
It seems that everything works well with `cross-spawn` and `q/.../`. 
I considered

```json
{
    "latex-workshop.latex.recipes": [
        {
          "name": "latexmk_copy",
          "tools": ["latexmk", "copyPDF"]
        }
    ],
    "latex-workshop.latex.tools": [
        {
          "name": "latexmk",
          "command": "latexmk",
          "args": [
            "-e",
            "$latex=q/pdflatex %O -synctex=1 -interaction=nonstopmode -file-line-error %S/",
            "-e",
            "$pdflatex=q/pdflatex %O -synctex=1 -interaction=nonstopmode -file-line-error %S/",
            "-outdir=%OUTDIR%",
            "-pdf",
            "%DOC%"
          ],
          "env": {}
        },
        {
          "name": "copyPDF",
          "command": "copy",
          "args": ["%OUTDIR%/t.pdf", "%OUTDIR%/b.pdf"],
          "env": {}
        }
    ]
}
```

https://github.com/jlelong/LaTeX-Workshop/actions/runs/67671244 passed

If you have a look at https://github.com/James-Yu/LaTeX-Workshop/compare/master...jlelong:test-cmd-exe, you will see that the only meaningful changes to make all this work are

- the direct use of `copy` as a real command instead of going through `cmd.exe``
- to spawn the recipes using `cross-spawn` instead of `child_process`.

**Comment by jlelong** [comment]
See https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#placeholders for the definitions of the new palceholders

**Comment by tamuratak** [comment]
Should we use `cross-spawn` also in `viewer.ts`? If there is not a specific reason, we had better leave it unchanged since we do not test external SyncTeX and those recipes are tricky.

https://github.com/James-Yu/LaTeX-Workshop/blob/a32dfdfe754e969fb9a4740d23b97e05f40650c0/src/components/viewer.ts#L5

**Comment by jlelong** [comment]
Correct, this is only used to launch the external viewer. I do not know if this feature is much used but `cross-spawn` should help in some cases.

Indeed, we still use `child_process` for external synctex

https://github.com/James-Yu/LaTeX-Workshop/blob/0d645610548c956236768606497bc19e06347be0/src/components/locator.ts#L427-L446
