### ISSUE TITLE
SyncTeX from cursor could open PDF if not already open.

### ISSUE THREAD

**Issue by FMuro** [James-Yu/LaTeX-Workshop#2046]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
With a LaTeX file open which has an associated PDF, SyncTeX from cursor could open the PDF if not already open and go to the cursor's position.

**Describe alternatives you've considered**
None.

**Additional context**
If I remember well TeXstudio had this behavior.

**Comment by jlelong** [comment]
We do not keep track of when a viewer is closed (this is not possible when using an external viewer) so it is not so obvious to decide when a new viewer should be launched and we could not do better than launching the default viewer. 

Because of all these limitations, I find it much simpler to simply tell the user to open a viewer first. We could pop up a notification.

**Comment by FMuro** [comment]
I hadn't thought of the case of external PDF viewer. A notification would also sound weird if an external PDF viewer is already open. Could this behavior depend on whether the configured PDF viewer is the integrated one?

**Comment by jlelong** [comment]
Actually, this is not straightforward for the internal viewer either. I am not aware of any way in vscode to keep track of when/if an editor is closed. Hence, imagine you open a viewer and then close it, the extension would not know about the closing. 

The best approach I can think of for now is to issue a notification pop up when no viewer has ever been opened. I do not think it is worth it trying to go beyond that.

**Comment by FMuro** [comment]
I see. I didn't know of all these difficulties. Now that I know, I think everything is well as it is. Thanks for taking the effort to answer!
