### ISSUE TITLE
Support go-to-symbol

### ISSUE THREAD

**Issue by karljs** [James-Yu/LaTeX-Workshop#212]
Thanks for working on this extension!  I'd really love to see support for browsing LaTeX symbols using the `go to symbol in X` features.  In particular, being able to navigate to any of the following by name would be extremely helpful to me:

- `\section`, `\subsections`, `\paragraph`, etc.
- `\label`
- `\newcommand`, `\renewcommand`, `\providecommand`, etc.

**Comment by James-Yu** [comment]
`\newcommand` etc should be possible, though I need to think again about it.
`\label` has already been supported. If it doesn't, please file another issue.
`\section` is not possible due to the limitation of LaTeX. When you are referencing a section, you have to reference through its `label` instead of the title. I would recommend you check out the LaTeX outline provided by the extension.
