### ISSUE TITLE
Outline view doesn't update when switching to subsections

### ISSUE THREAD

**Issue by musm** [James-Yu/LaTeX-Workshop#2164]
1. Create a document with multiple sections and subsections.

As you move around with the cursor, the outline view updates to the section correct, _but it does not update to the subsections!
![1](https://user-images.githubusercontent.com/4319522/84955361-2c823c80-b0c5-11ea-9b6f-ab676d971c42.gif)
_

**Comment by tamuratak** [comment]
Fill out all the information required in the issue template. Please paste the whole log messages here, not parts of ones. It should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

![スクリーンショット 2020-02-14 20 41 25](https://user-images.githubusercontent.com/10665499/74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524.png)

**Comment by tamuratak** [comment]
## Preliminary questions [Required]

### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes/No

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes/No

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes/No




## Describe the bug [Required]

A clear and concise description of what the bug is.

### To Reproduce

Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. See error

### Expected behavior

A clear and concise description of what you expected to happen.




## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'.

[Paste the log here]
```

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools' -> 'Console'. Paste anything suspicious.

[Paste the log here]
```



## Screenshots

If applicable, add screenshots to help explain your problem.




## Desktop [Required]
 - OS: [e.g. Windows 10]
 - VS Code version: [e.g. 1.41.0]
 - Extension version: [e.g. 8.5.0]
 - TeX distribution version: [e.g. TeX Live 2019/MiKTeX 2.9.7250]




## Additional questions

### Are you using LaTeX Workshop with VS Code Remote?

Yes/No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 0.48.0]

### Additional context

Add any other context about the problem here.

**Comment by musm** [comment]
## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
[19:18:08] Initializing LaTeX Workshop.
[19:18:08] Creating file watcher for .pdf files.
[19:18:09] Creating LaTeX Workshop http and websocket server.
[19:18:09] LaTeX Workshop initialized.
[19:18:09] Found root file from active editor: c:\Users\Mus\OneDrive\Desktop\latex\report.tex
[19:18:09] Root file changed from: undefined to c:\Users\Mus\OneDrive\Desktop\latex\report.tex. Find all dependencies.
[19:18:09] Instantiating a new file watcher for c:\Users\Mus\OneDrive\Desktop\latex\report.tex
[19:18:09] Creating file watcher for .bib files.
[19:18:09] Parsing c:\Users\Mus\OneDrive\Desktop\latex\report.tex
[19:18:09] Found .bib file C:\Users\Mus\OneDrive\Work\Library\main.bib
[19:18:09] Adding .bib file C:\Users\Mus\OneDrive\Work\Library\main.bib to bib file watcher.
[19:18:09] Parsing .bib entries from C:\Users\Mus\OneDrive\Work\Library\main.bib
[19:18:09] Parse fls file.
[19:18:09] Fls file found: c:\Users\Mus\OneDrive\Desktop\latex\out\report.fls
[19:18:09] Server created on 127.0.0.1:60992
[19:18:09] Adding c:\Users\Mus\OneDrive\Desktop\latex\report.tex to file watcher.
[19:18:10] LaTeX Workshop version: 8.10.0
[19:18:10] Snippet data loaded.
[19:18:10] Parsed 521 bib entries from C:\Users\Mus\OneDrive\Work\Library\main.bib.
```


### Developer Tools Console [Required]

```
[ms-vscode.powershell]: Command `workbench.action.debug.start` appears multiple times in the `commands` section.
abstractExtensionService.ts:400 [ms-vscode.powershell]: Command `workbench.action.closePanel` appears multiple times in the `commands` section.
abstractExtensionService.ts:400 [ms-vscode.powershell]: Command `workbench.action.positionPanelLeft` appears multiple times in the `commands` section.
abstractExtensionService.ts:400 [ms-vscode.powershell]: Command `workbench.action.positionPanelBottom` appears multiple times in the `commands` section.
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope text.bibtex.
Old grammar file: file:///c%3A/Users/Mus/.vscode/extensions/james-yu.latex-workshop-8.10.0/syntax/Bibtex.tmLanguage.json.
New grammar file: file:///c%3A/Users/Mus/.vscode/extensions/torn4dom4n.latex-support-3.2.0/grammars/BibTeX.json
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope text.tex.latex.
Old grammar file: file:///c%3A/Users/Mus/.vscode/extensions/james-yu.latex-workshop-8.10.0/syntax/LaTeX.tmLanguage.json.
New grammar file: file:///c%3A/Users/Mus/.vscode/extensions/torn4dom4n.latex-support-3.2.0/grammars/LaTeX.json
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope text.tex.
Old grammar file: file:///c%3A/Users/Mus/.vscode/extensions/james-yu.latex-workshop-8.10.0/syntax/TeX.tmLanguage.json.
New grammar file: file:///c%3A/Users/Mus/.vscode/extensions/torn4dom4n.latex-support-3.2.0/grammars/TeX.json
register @ TMScopeRegistry.ts:45
2console.ts:137 [Extension Host] (node:6320) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ console.ts:137
```

## Desktop [Required]
 - OS: Windows 10 
 - VS Code version: 1.46.0
 - Extension version:  8.10.0
 - TeX distribution version:  TeX Live 2020


You visited the wiki?: Yes


You can compile a TeX document manually?: Yes

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by jlelong** [comment]
Please use the _Structure_ view in the TeX panel, which is the structure view we fully implement in the extension.

**Comment by musm** [comment]
Can we move the structure view or replace it with the outline view? It just seems that the Structure view is exactly what the outline view should be.

I never really use the TeX panel.

**Comment by tamuratak** [comment]
You can use drag and drop the view.

See https://code.visualstudio.com/updates/v1_46#_flexible-layout
