### ISSUE TITLE
Selecting a completion item with `Enter` does not insert the item again

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#2167]
I see the issue of #2151 again. 2bd2896dcc1d5b55ff402df1a21cadbd278db925 has gone in the current master after merging `2128-weave.jl-support`.

@jlelong I am not sure why the commit log after merging `2128-weave.jl-support` becomes the current one.

**Comment by jlelong** [comment]
I have probably screwed up the merge, which was a bit tricky because there had been a lot of changes in master. I hope this is fixed for good now.

I will make an other PR on this as I have just discovered the existence of  the condition `acceptSuggestionOnEnter`. Hence, I guess we could duplicate entries and use

```json
{
        "command": "latex-workshop.onEnterKey",
        "key": "enter",
        "when": "editorTextFocus && acceptSuggestionOnEnter && !suggestWidgetVisible && !editorReadonly && editorLangId =~ /latex|rsweave|jlweave/ && !vim.active"
},

{
        "command": "latex-workshop.onEnterKey",
        "key": "enter",
        "when": "editorTextFocus && !acceptSuggestionOnEnter && !editorReadonly && editorLangId =~ /latex|rsweave|jlweave/ && !vim.active"
}
```

**Comment by jlelong** [comment]
I have implemented the above solution. I do hope everything works fine in all cases this time.

**Comment by tamuratak** [comment]
I have not seen any issues so far.
