### ISSUE TITLE
Magic comment should count for dependency

### ISSUE THREAD

**Issue by JimmyZJX** [James-Yu/LaTeX-Workshop#2211]
**Is your feature request related to a problem? Please describe.**
See #2210 

**Describe the solution you'd like**
When a magic comment is specified, the tex file should be considered as a dependency to the root file, even if the dependency solver didn't find any direct evidence.
As a result, any change to that tex file should initiate a rebuild on the root file.

**Describe alternatives you've considered**
Add a "onSaveOrChange" to `latex-workshop.latex.autoBuild.run` options:

When Saving a "tex" file in VSCode (e.g. Ctrl-S), if the file is not being watched for changes (when the dependency is not calculated correctly), find the root LaTeX file and compile it.

**Additional context**
See #2210

**Comment by jlelong** [comment]
I do not really feel like adding as dependencies any file not explicitly listed as such. See [the wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#Multi-File-Projects) to know more about dependency computations.

I can add  a `onSaveOrChange` option to `latex-workshop.latex.autoBuild.run`, which used to exist but was removed because most of the time it would simply achieve the same as `onFileChange`.

**Comment by JimmyZJX** [comment]
Thanks for the reply, that would be great for me!
(and perhaps saves people using WSL2; they need to use polling if they want to enjoy the auto-build feature)
