### ISSUE TITLE
Colour text inside a \text{ } block white like normal text

### ISSUE THREAD

**Issue by MiguelGuthridge** [James-Yu/LaTeX-Workshop#2215]
**Describe the solution you'd like**
Text inside a `\text{ }` block would be coloured white to indicate it is plaintext.

**Describe alternatives you've considered**
.... not having this feature? It'd just be a neat enhancement - it isn't essential.

**Additional context**
![image](https://user-images.githubusercontent.com/31365175/87854181-7f187800-c953-11ea-8d44-a4293b3e8932.png)

**Comment by jlelong** [comment]
Unfortunately, this is easier said than done as this would require to match  the pair `{...}` in `\text{...}`. Because `{...}` can be nested inside `\text{...}`, this is really difficult using the textmate regex language. 
The best we could do is to match `\text{...}` with one level of nesting allowed.

**Comment by jlelong** [comment]
I mean that the content of `text` would only be matched if it contains less than 1 level of nesting ˋ{}`. Either the whole content is matched or none

**Comment by jlelong** [comment]
Thinking about this twice, the benefits of changing the highlighting of the content of `\text{...}` are too little considering how delicate it is. It is not enough to declare the content as normal text, it should be also matched against the whole grammar because in constructions like `\text{if $a<b$}`, `$a<b$` should be highlighted as maths.

**Comment by tamuratak** [comment]
One possible solution is using [semantic highlight](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide), which needs a lot of work to do.

Another solution is:

- Set a new textmate scope to `\text{ ... }`.
- Users [customize](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#customizing-a-color-theme) a color theme they are using for the scope if they want.

**Comment by MiguelGuthridge** [comment]
Yeah it may be a thing to look into in the long term, but probably not worth the effort right now.

**Comment by jlelong** [comment]
> Set a new textmate scope to `\text{ ... }`.

Well, the real difficulty is to match `\text{...}` because of brace nesting and moreover the content of `\text{....}` should be matched against the whole LaTeX syntax.
