### ISSUE TITLE
autoBuild when using external build command and no rootFile specified

### ISSUE THREAD

**Issue by michael-vacek** [James-Yu/LaTeX-Workshop#2218]
Hi all,

is it possible to use autoBuild function (latex-workshop.latex.autoBuild.run) if I use external command (latex-workshop.latex.external.build.command)? 

Also, I dont have rootFile specified. Is it needed for this function or it cannot be used without rootFile specified?

Thanks,
Michael

**Comment by jlelong** [comment]
The detailed explanations are in the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#Multi-File-Projects). Here is a short summary as the page is quite lengthy

- external build command completely bypasses the root file detection and the recipes mechanism
- With `latex-workshop.latex.autoBuild.run: "onFileChange"`, auto build only works with a root File because it is a file watcher to monitor changes in all the `tex` dependencies.
- With `latex-workshop.latex.autoBuild.run: "onSave"`, building is triggered whenever a file is saved inside VSCode. This works with external build commande. Note that this was reintroduced in 49a55b4 and is not available in `8.11.1` (will be in the next release).
