### ISSUE TITLE
Consider ConTeXt support

### ISSUE THREAD

**Issue by jonasgloning** [James-Yu/LaTeX-Workshop#2231]
**Is your feature request related to a problem? Please describe.**
I recently switched to ConTeXt for some documents. It is much easier to use, much more programmable and (surprisingly?) much faster. Until now, there is no proper extension that works with ConTeXt and the ones I tried conflict with LaTeX-Workshop. 

**Describe the solution you'd like**
ConTeXt-Support in LaTeX-Workshop.
My wishlist, In decreasing order of importance:
- proper autocompletion
- syntax highlighting
- autoindentation

**Describe alternatives you've considered**
Switching to TeXworks for ConTeXt-Documents or abandon ConTeXt.

**Additional context**
I think that most of the extension is already suitable for ContTeXt. PDF preview with SyncTeX is already working, recipes and tools are customizable. There is already support for `rsweave` and `jlweave`, two non-latex languages. (I don't know them and can't comment on their level of support).

I am willing to help and implement a big part of it myself. I would need some help to get started however — I don't have much experience with writing VSCode extensions yet.

**Comment by jlelong** [comment]
I am not familiar with ContTeXt, but as far as I can see it is a completely different language from LaTeX. The `rweave` and `jlweave` documents are basically LaTeX documents with some extra R or Julia code.

The situation with ContTeXt is totally different, a ContTeXt document does not look like a LaTeX document with extra parts. Adding support for ContTeXt would require to rewrite most of the extension because the LaTeX parser would fail and therefore most features would not work. I believe it should be implemented in a dedicated extension.
