### ISSUE TITLE
Building with 'onFocusChanged'

### ISSUE THREAD

**Issue by ChristianNavolskyi** [James-Yu/LaTeX-Workshop#2236]
**Is your feature request related to a problem? Please describe.**
When running on power build every time the document is saved (therefore changed) isn't too bad, but when running on battery it can become quite resource-intensive and drain the battery.

**Describe the solution you'd like**
It would be nice if the document could be built only when the focus changes to another tab in VS Code. To look at the PDF you would have to switch anyway so it would be a good trigger I guess.

**Comment by jlelong** [comment]
I think we can only monitor when a tab gets the focus but not when it looses it, which makes a `onFocusChanged` option hard and tricky to implement.

When running on battery, you could deactivate auto build and manually trigger build using `alt-ctrl-b`.

FYI, vscode has an internal backup mechanism to save your edits every time you stop typing for more than 1 second. If you restart vscode after a crash or power failure, your files will be marked as dirty because the non saved edits were restored from the backups. So, you do not actually need to save your document for security reasons but only when you actually mean it
