### ISSUE TITLE
LanguageTool integration

### ISSUE THREAD

**Issue by Laberbear** [James-Yu/LaTeX-Workshop#225]
I recently found a great spellchecking tool called LanguageTool (https://www.languagetool.org/)

It can be used to spellcheck quite a lot of languages and I'm currently copying the LaTeX segments out of VS Code into their GUI to get atleast the obvious typos and grammar stuff out of my writing.

There is already an extension for VS Code, that makes use of a LanguageTool server, however it doesn't work with LaTeX yet:
https://marketplace.visualstudio.com/items?itemName=adamvoss.vscode-languagetool

I'm not sure whether this is out of the scope for LaTeX-Workshop, but in my opinion pretty much everyone uses LaTeX to write articles/papers/texts which definitely could benefit from that.

Best regards,
Laberbear

**Comment by James-Yu** [comment]
Thanks for the suggestion.

As you may know, previously we decided to add a build-in spell checker. But later the code was scrapped since we found a better solution, i.e., cSpell. If this LT extension can do the similar thing, I would be more than happy to integrate some introductions to the README, in which we already have some lines on cSpell.

If you consider this as a good alternative, would you mind fork and edit the README with your recommendation? Will accept PR on this.

**Comment by Laberbear** [comment]
Sadly the existing extension doesn't support LaTeX right now and isn't as flexible as CodeSpellcheck. :/

**Comment by James-Yu** [comment]
```
"cSpell.ignoreRegExpList": [
  "\\\\\\w*(\\[.*?\\])?(\\{.*?\\})?",
  "\\$.+?\\$"
]
```
works really well for me. You may have a try.

**Comment by Laberbear** [comment]
Yeah, but sadly cSpell only supports english right now. (I tried adding my own dictionary, but it was a huge mess).
Whereas LanguageTool supports 20+ languages and also has some grammar checking magic in it.

**Comment by bartosz-antosik** [comment]
If you are on Windows (but this is going to change very soon) and looking for a multi language spell checker for LaTeX then you may want to give a try to [Spell Right](https://marketplace.visualstudio.com/items?itemName=ban.spellright).

I am the author, and I reckon I had a very different approach than cspell (which you can read with multiple details in the description of the [Spell Right](https://marketplace.visualstudio.com/items?itemName=ban.spellright) and here [#20266](https://github.com/Microsoft/vscode/issues/20266)) and Language Tool, but it is multi language (e.g. spelling multiple languages in single LaTeX document) is strongly concentrated on being precise (e.g. spelling of short words & abbreviations), unobtrusive, CPU efficient (differential spelling) and have good integration with good dictionaries (currently native Windows Spelling API, soon macOS NSSpellChecker & hunspell in linux) for many languages.

**Comment by James-Yu** [comment]
Glad to know the growth of vscode extension and spell checker community! When I was doing the research, the only available option is cSpell. I will check out the above options and see if they can be integrated into README.

**Comment by James-Yu** [comment]
I've just tried out Spell Right and find it quite good! However, logging the mis-spells as error seems a bit overwhelming especially on LaTeX. The compiler error is easily overlook when stuck in the sea of mis-spells, especially when there are piles of different technical terminologies.

Another thing I noticed is that the words in equations are also checked, e.g., in `\forall(i,j)\notin\mathcal{E}` the first `i` is labeled as a mis-spell, which obviously should be ignored.

@bartosz-antosik do you need a separate issue in your repo on these things? Other than that, it works quite well for me.

I'm yet to check out the LTools. Installing multiple extensions for checking English is a bit frightening to me.

**Comment by bartosz-antosik** [comment]
@James-Yu: It is absolutely enough to have this notification here. I will look into the latex parser. Just could you maybe show bit larger part of the document? I remember excluding math from spelling and it is not clear to me what have I missed out.

Logging spelling errors in red has been risen among my issues some ago. I thought that:

1) usability - it is general practice, from word processors to web browsers everywhere it is underlined in red zig-zag line. Having green for (spelling) error seems odd. But it's of course a personal taste.
2) VSCode's interface generally is not very favorable for spell checkers. The whole mechanism is bit strange (e.g. no right context menu to look for correction etc.)

I have decided to leave is as it is because most of what can be done is to configure some settings choice to log it as warnings but I felt no pressure. I will meditate on this. ;-)

P.S. I have just realized how much of a bragging my previous post was. Sorry about this.

**Comment by bartosz-antosik** [comment]
I have created issue [#35](https://github.com/bartosz-antosik/vscode-spellright/issues/35) to discuss the case of math spelled unnecessarily. Also you may be interested in [#34](https://github.com/bartosz-antosik/vscode-spellright/issues/34) as it seems to me (but I may not understand LaTeX deep enough) that your RegExp for cspell suffers same flaw.

**Comment by James-Yu** [comment]
Thanks for the discussion. I will find a time to have a PR on controllable diagnostic channel. Let's switch to the other issue thread for related discussion. 😄

**Comment by James-Yu** [comment]
Both new extensions credited in readme. Close this issue for now but open for new suggestions/discussion.
