### ISSUE TITLE
Auto build doesn't use recipe as in settings

### ISSUE THREAD

**Issue by Yi-yi** [James-Yu/LaTeX-Workshop#2263]
I am using `Xelatex` for compiling. Here are my settings:

```
    "latex-workshop.latex.recipes": [
        {
            "name": "latexmk 🔃",
            "tools": [
              "latexmk"
            ]
        },]

    "latex-workshop.latex.tools": [
        {
            "name": "latexmk",
            "command": "latexmk",
            "args": [
                "-xelatex",
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "%DOC%"
            ]
        },
        {
            "name": "bibtex",
            "command": "bibtex",
            "args": [
                "%DOCFILE%"
            ]
        }
    ],
```
In the setting `Latex-workshop › Latex › Recipe: Default`, I make it to `first` (while there only exists one recipe).

When I use the command `Build with recipe` and choose `latexmk`, the file compiles correctly,  it uses `Xelatex` as I can see from the "LATEX Compilation Live Info". But when the file is auto-building, it keeps using `pdftex`. And the command `Build latex project` (`Ctrl + Alt + B`) invokes `pdftex` as well. Is there any way to switch from `pdftex` to `XeLatex`?

**Comment by jlelong** [comment]
Please post the complete logs of the extension. Do not truncate or alter them.

![74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524](https://user-images.githubusercontent.com/2910140/77959270-98c77e00-72d6-11ea-8c58-4934a9fde39a.png)

**Comment by Yi-yi** [comment]
Hi @jlelong, thank for your response. Here is the compiler log when I use the command `Build latex project` (`Ctrl + Alt + B`):

```
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (MiKTeX 20.7)
entering extended mode
("c:/Users/Yi-yi/Google Drive/ComputerScience/LaTex/texworks/untitled-3.tex"
LaTeX2e <2020-02-02> patch level 5
L3 programming layer <2020-08-07> ("C:\Program Files\MiKTeX\tex/latex/base\article.cls"
Document Class: article 2019/12/20 v1.4l Standard LaTeX document class
("C:\Program Files\MiKTeX\tex/latex/base\size11.clo")) ("C:\Program Files\MiKTeX\tex/latex/base\inputenc.sty") ("C:\Program Files\MiKTeX\tex/latex/fontspec\fontspec.sty" ("C:\Program Files\MiKTeX\tex/latex/l3packages/xparse\xparse.sty" ("C:\Program Files\MiKTeX\tex/latex/l3kernel\expl3.sty" ("C:\Program Files\MiKTeX\tex/latex/l3backend\l3backend-pdfmode.def")) ("C:\Program Files\MiKTeX\tex/latex/l3packages/xparse\xparse-generic.tex"))

C:\Program Files\MiKTeX\tex/latex/fontspec\fontspec.sty:45: Fatal Package fontspec Error: The fontspec package requires either XeTeX or
(fontspec)                      LuaTeX.
(fontspec)                      
(fontspec)                      You must change your typesetting engine to,
(fontspec)                      e.g., "xelatex" or "lualatex"instead of
(fontspec)                      "latex" or "pdflatex".

Type <return> to continue.
 ...                                              
                                                  
l.45 \msg_fatal:nn {fontspec} {cannot-use-pdftex}
```
This is the same as the error message in TexWorks when I use `pdfLatex` engine for compiling. In TexWorks I would switch to `XeLatex` in the `Typeset`  and it works well.

**Comment by tamuratak** [comment]
It is not the log we are asking. Please paste `LaTeX Workshop extension log`.  It should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

You must fill out all the information required in the issue template.

## Preliminary questions [Required]

### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes/No

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes/No

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes/No




## Describe the bug [Required]

A clear and concise description of what the bug is.

### To Reproduce

Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. See error

### Expected behavior

A clear and concise description of what you expected to happen.




## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'.

[Paste the log here]
```

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools' -> 'Console'. Paste anything suspicious.

[Paste the log here]
```



## Screenshots

If applicable, add screenshots to help explain your problem.




## Desktop [Required]
 - OS: [e.g. Windows 10]
 - VS Code version: [e.g. 1.41.0]
 - Extension version: [e.g. 8.5.0]
 - TeX distribution version: [e.g. TeX Live 2019/MiKTeX 2.9.7250]




## Additional questions

### Are you using VSCodium?

Yes/No

### Are you using LaTeX Workshop with VS Code Remote?

Yes/No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 0.48.0]

### Additional context

Add any other context about the problem here.

**Comment by tamuratak** [comment]
Please notify if any progress.

**Comment by CheariX** [comment]
I could confirm the problem.
In my case, i had *misconfigured* the tool as follow:
```json
{
          "name": "latexmk",
          "command": "latexmk",
          "args": [
            "-xelatex",
            "-synctex=1",
            "-interaction=nonstopmode",
            "-file-line-error",
            "-pdf", // DELETE THIS LINE TO WORK
            "-outdir=%OUTDIR%",
            "%DOC%"
          ]
        }
```

After removing `-pdf`, it worked for me.
