### ISSUE TITLE
The folding property in syntax.json

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#2407]
Related to #1716 and #2406. We have the `folding` property in `syntax.json`:

https://github.com/James-Yu/LaTeX-Workshop/blob/bf88c38af6f647f8fa3cc2b7e931956d93526be9/syntax/syntax.json#L55-L60

It has no effect because we define a `FoldingProvider`.  Can we remove the property? 

We have the same property in the following files:

https://github.com/James-Yu/LaTeX-Workshop/blob/8e7f1da4700892ad3e4cf6ae9f5c8dde32273dd7/syntax/syntax-expl3.json#L55-L60

https://github.com/James-Yu/LaTeX-Workshop/blob/8e7f1da4700892ad3e4cf6ae9f5c8dde32273dd7/syntax/syntax-doctex.json#L51-L56

https://github.com/James-Yu/LaTeX-Workshop/blob/bf88c38af6f647f8fa3cc2b7e931956d93526be9/syntax/syntax-weave.json#L59-L64

The one in `syntax-doctex.json` has an effect since we do not define any `FoldingProvider` for doctex files.

**Comment by jlelong** [comment]
Googling around a bit, I understand that a registered folding ranges provider overwrites the region markers mechanism. 

Relying on `#region` / `#endregion` pair seems standard in many languages. I think we should consider adding it to our  folding ranges provider.

**Comment by VolodyaRybakov** [comment]
I'm not sure that this will work completely correctly, but I was quite satisfied with this functionality. (I tested this code on my LaTeX project)

I think you can just paste this code snippet into your file `folding.js`:

```
getRegionFoldingRanges(document) {
        const ranges = [];
        const opStack = [];
        const text = document.getText();
        const envRegex = /(?:(region)|(Region)(?=$|%|\s|\\|\[.*\]))|(?:(endregion)|(Endregion)(?=$|%|\s|\\))/g; // added [...] for compatibility with the Colored Regions extension from mihelcic
        let match = envRegex.exec(text); // init regex search
        while (match) {
            //for 'region': match[1] contains 'region',  keyword is 'region'
            //for 'Region':   match[2] contains 'Region', keyword is 'Region'
            //for 'endregion': match[3] contains 'endregion', keyword is 'region'
            //for 'Endregion': match[4] contains 'Endregion', keyword is 'Region'
            const item = {
                keyword: match[1] ? 'region' : (match[2] ? 'Region' : (match[3] ? 'region' : 'Region')),
                index: match.index
            };
            const lastItem = opStack[opStack.length - 1];
            if ((match[3] || match[4]) && lastItem && lastItem.keyword === item.keyword) { // match 'endregion' with its 'region'
                opStack.pop();
                ranges.push(new vscode.FoldingRange(document.positionAt(lastItem.index).line, document.positionAt(item.index).line - 1));
            }
            else {
                opStack.push(item);
            }
            match = envRegex.exec(text); //iterate regex search
        }
        //TODO: if opStack still not empty
        return ranges;
    }
```

and edit the 32 line of code as follows

```
return [...this.getSectionFoldingRanges(document), ...this.getEnvironmentFoldingRanges(document), ...this.getRegionFoldingRanges(document)];
```

The only thing I insist on is saving `[...]` after `%region` to keep compatibility with the *Colored Regions* extension from *mihelcic*.

I will be happy if it turns out to be useful.

**Comment by tamuratak** [comment]
Ref 

- https://github.com/microsoft/vscode/issues/50991#issuecomment-394316235

**Comment by jlelong** [comment]
From https://code.visualstudio.com/api/language-extensions/language-configuration-guide#folding, there are three kinds of folding

- Indentation-based folding
- Language configuration folding using markers
- Language server folding using a folding range provider

https://github.com/microsoft/vscode/issues/50991#issuecomment-394316235 refers to indentation based folding. This issue is discussing the precedence of language server folding over folding region markers introduced in [vscode 1.22](https://code.visualstudio.com/docs/editor/codebasics).

**Comment by tamuratak** [comment]
Ref

- https://github.com/microsoft/vscode/blob/14bf08070504ba8ab2a24af353d0a58472e0609a/src/vs/editor/contrib/folding/folding.ts#L250-L272

**Comment by jlelong** [comment]
Thanks for the references. Now, this is clear that a folding range provider takes precedence.
