### ISSUE TITLE
Add autocompletion support for custom commands

### ISSUE THREAD

**Issue by tobiasdiez** [James-Yu/LaTeX-Workshop#2511]
**Is your feature request related to a problem? Please describe.**
I have a couple of commands defined in a custom package using a custom command (which serves as an enhanced alias around NewDocumentCommand). If I include this package in a latex document, I get no autocompletion of the commands defined in this file.

**Describe the solution you'd like**
A way to provide a list of custom commands that should be added to the autocompletion.

**Describe alternatives you've considered**
Create snippets for each command, but that gets tedious very quickly.

**Comment by jlelong** [comment]
Intellisense for commands is described on https://github.com/James-Yu/LaTeX-Workshop/wiki/Intellisense#commands

It is not possible to scan packages for newcommands because their syntax is too complex. Note that once a command has been used, a snippet is dynamically built for it and it is added to the command completion list.

**Comment by tobiasdiez** [comment]
I couldn't find anything in the documentation that would help in this situation. What did you had in mind?

> It is not possible to scan packages for newcommands because their syntax is too complex.

I agree! That's why I suggested to add a setting where users can add their own custom commands that are added to the intellisense.

**Comment by jlelong** [comment]
> I couldn't find anything in the documentation that would help in this situation. What did you had in mind?

Put your custom commands in a separate `macros.tex` file and add `\input{macros.tex}` to your main file. If you want to keep the definitions inside your package file, you can use a fake inclusion

```latex
\iffalse
  \input{macros.tex}
\fi
```

**Comment by tamuratak** [comment]
Please define user snippets.

- https://code.visualstudio.com/docs/editor/userdefinedsnippets#_create-your-own-snippets

**Comment by tobiasdiez** [comment]
> Put your custom commands in a separate `macros.tex` file and add `\input{macros.tex}` to your main file.

Thanks, that works. However, it feels like an ugly hack. Wouldn't it be nicer to have a setting where the user can add the path to the commands file?

> You can also define user snippets.

Thanks, but as I said, I already considered this option and for 200 commands this is just too tedious and repetitive!

**Comment by tamuratak** [comment]
Out of the scope of the extension.

**Comment by jlelong** [comment]
> However, it feels like an ugly hack

It is not actually. The parser does not execute TeX macros, hence you can use `\iffalse ... \fi` blocks to add information to the parser while hiding it from the compiler. This has already proved powerful to solve issues because of non standard usage.

> Thanks, but as I said, I already considered this option and for 200 commands this is just too tedious and repetitive!

Consider writing a script to generate the snippets. 

1. You could write a `.cwl` file for your package (see [here](https://github.com/LaTeXing/LaTeX-cwl))
2. Use the function `parse_cwl_file` from [`pkgcommand.py`](https://github.com/James-Yu/LaTeX-Workshop/blob/d530c0f4b977b9bab7fbe44182efe9df30e0a86e/dev/pkgcommand.py). Dump the objects in `.json` format following https://github.com/James-Yu/LaTeX-Workshop/blob/d530c0f4b977b9bab7fbe44182efe9df30e0a86e/dev/pkgcommand.py#L214-L223
3. Copy the two `_cmd.json` and `_env.json` files into the directory `data/packages/` inside the extension.

**Comment by jlelong** [comment]
From @tobiasdiez 

> The solution with the cwl file is awesome. I already have a cwl file and having an option to load that into latex-workshop would be nice. Thanks for the suggestion! Maybe something to add to the documentation?

I am afraid it does not work out of the box. Things to be done before documenting it

- Provide a ready to use script to generate the `_cmd.json` and `_env.json` files from the `.cwl` file
- Provide a setting to specify an additional directory where to look for `_{cmd,env}.json` files to avoid having to copy these files into the extension directory after every update.

I will think of it and try to make a PR in the coming days. I will let you know such that you can test it.

**Comment by jlelong** [comment]
See https://github.com/James-Yu/LaTeX-Workshop/wiki/Intellisense#commands for how to generate your intellisense data.
