### ISSUE TITLE
Disable optional arguments in Intellisense completed commands

### ISSUE THREAD

**Issue by stephbur** [James-Yu/LaTeX-Workshop#2583]
I have many small commands defined that take a single argument and no optional arguments.
When using the Intellisense autocomplete the command appears as `\examplecmd[]{}`. I then always have to tediously delete the square brackets first. Can I somehow make it always show `\examplecmd{}` rather than `\examplecmd[]{}` when auto-completing?

I think this was the case for older versions (> 1 year) of LaTeX-workshop, but I could not find anything in the settings.

**Comment by jlelong** [comment]
Please post an example to reproduce the issue because the extension should detect whether a command takes optional arguments. It may also be related to [`latex-workshop.intellisense.optionalArgsEntries.enabled`](https://github.com/James-Yu/LaTeX-Workshop/wiki/Intellisense#latex-workshopintellisenseoptionalArgsEntriesenabled)

**Comment by stephbur** [comment]
I have a separate file in my project where I define a lot of commands like the following:

`\newcommand\muamps[1]{\SI{#1}{\micro\ampere}}`

I disabled the setting you mentioned, without it having any effect.

**Comment by jlelong** [comment]
This is because, the standard LaTeX syntax expects the command name to appear inside braces

```
\newcommand{\muamps}[1]{\SI{#1}{\micro\ampere}}
```
