### ISSUE TITLE
Highlighting breaks after defining new commands

### ISSUE THREAD

**Issue by romanovzky** [James-Yu/LaTeX-Workshop#271]
### How to reproduce

1. Define in the preamble
```TeX
\newc{\beq}{\begin{equation}}
\newc{\eeq}{\end{equation}}
\newc{\bea}{\begin{eqnarray}}
\newc{\eea}{\end{eqnarray}}
``` 

### Expected behavior

[Imgur](https://i.imgur.com/TXFxlNB.png)

### Actual behavior
[Imgur](https://i.imgur.com/9SfzoTf.png)

### Additional Information
Arch Linux

**Comment by James-Yu** [comment]
This is due to the fact that vscode highlighter cannot properly distinguish
```
\newc{\beq}{\begin{equation}}
```
from 
```
\begin{equation}
```
and assume that the former one initiates a math environment. Therefore the following contents are rendered as is.

Unfortunately, this seems not to be a solvable issue from the extension side. A dirty hack is
```
\newc{\beg}{\begin}
\newc{\beq}{\beg{equation}}
\newc{\eeq}{\end{equation}}
```

I will close this issue for now, and revisit it if the syntax highlight syntax were changed.
