### ISSUE TITLE
How can I use tikz in latex workshop,  vscode,  win10?

### ISSUE THREAD

**Issue by YiranCdr** [James-Yu/LaTeX-Workshop#294]
Hi,
I would like to draw a tree in latex, but find it difficult to set an environment for `tikz`. I‘ve  also downloaded `tikz` source code from SourceForge. I have tried to look for `latex-workshop.latex.toolchain`, but i just don't know how to change the settings. Could you help me?

**Comment by James-Yu** [comment]
I don't have any experience in tikz, but I would figure that it is just another compiler. If so, you may refer to the README for more information, especially the toolchain section.

We also have some other users who use the extension for tikz processing. You may find some by searching for tikz-related issues in this repository.

**Comment by YiranCdr** [comment]
thanks for your reply~
well, it seems that by using `tikz` I could add pertain package and create graphics programmatically in latex. I have read the toolchain section. The question is how can I add it into latex workshop, just like add a lib into a c++ program project?
sorry for the bit stupid question= =. I'm so fresh in this area.

**Comment by tku137** [comment]
Setting the appropriate file association in vscode user or workspace settings will enable syntax highlighting and so on, if this is what's meant by "add it into latex workshop". The setting is:

```
"files.associations": {
    "*.tikz": "latex"
}
```

**Comment by James-Yu** [comment]
@YiranCdr I would suppose your problem is `tikz`-related, instead of extension-related. This extension can (and can only) call the `tikz` compiler according to the instruction by the toolchain config. How to include `tikz` packages into source file is beyond our reach. You may find [this](http://www.texample.net/tikz/resources/) link useful.

I will close this issue for now (re-open certainly possible). Further discussions are always welcomed.
