### ISSUE TITLE
`\bm` is duplicated in completion items

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#3174]
`\bm` is duplicated in completion items. Notice that the two `\bm` behaviors are slightly different since `\bm{math expression}` has a placeholder and the selected `\bm` doesn't.

![2022-03-02 9 36 58](https://user-images.githubusercontent.com/10665499/156272529-dff80b42-2177-4617-a941-d25cc77a8788.png)

```latex
\documentclass[12pt]{article}
\usepackage{amsmath}
\usepackage{bm}

\begin{document}
\begin{align*}
  \bm{A}
\end{align*}
\begin{align*}
  \bm
\end{align*}
\end{document}
```

**Comment by jlelong** [comment]
In the example, the package `beamerfoils` is not loaded, so this is not the reason of the second `\bm`. Duplicates are actually already handled by

https://github.com/James-Yu/LaTeX-Workshop/blob/584614846fe428313870e8d43ebb22f7f516cb53/src/providers/completer/command.ts#L385-L387

Note that `getCmdName` returns `bm{}` for the two entries cited above. 

The duplication is computed based on the `filterText` field when defined

https://github.com/James-Yu/LaTeX-Workshop/blob/584614846fe428313870e8d43ebb22f7f516cb53/src/providers/completer/command.ts#L207-L215

The suggested item `\bm` comes from the parsing of the file to scan the user commands. The problem comes from https://github.com/James-Yu/LaTeX-Workshop/blob/d08775a743de260c0d73865487ad62b13a5feb43/src/providers/completer/commandlib/commandfinder.ts#L73-L82 where `filterText` does not contain a bracket pair for every argument.
