### ISSUE TITLE
Feature Request: Consider using the customEditor api

### ISSUE THREAD

**Issue by ManuelHentschel** [James-Yu/LaTeX-Workshop#3337]
Could you please reconsider using the customEditor api for the pdf viewer provided by this extensions?

I already implemented this in https://github.com/James-Yu/LaTeX-Workshop/pull/3069, which was promptly rejected and locked.

For the last half year I have been using a custom fork of this repo, just because viewing pdf files works so much smoother when using the customEditor api properly. I have not experienced any disadvantages of this approach and think it would be a great UX improvement for every user. If you know any problems that might arise from this change, I'll be happy to investigate and fix.

**Comment by tamuratak** [comment]
Rejected with the same reason.

**Comment by James-Yu** [comment]
May I call for a discussion on this issue @tamuratak ? I have checked the previous PR and the api, and did not notice increased maintain burden if it is accepted. Also seems to be a welcoming improvement.

**Comment by tamuratak** [comment]
No. Please trust my decision.

- One of the maintainers' jobs is saying no. Please learn to say no to requests from users.
- Remember that, for the maintenance burden,  I had to remove fancy features you have merged pull requests from users. 
- You feel good that users say "thank you" to you when you merge pull requests. And, I am bothered to maintain the feature and eventually decide to remove the feature. It is totally unfair.
- You cannot join a discussion without understanding the basic architecture. I don't want to be bothered to explain the technical details of every decision  to you.

**Comment by James-Yu** [comment]
I cannot trust anyone without justification.

1. Is this a fancy feature or a replacement of out-of-date api?
2. It's not your obligation to maintain the features. I do not feel unfairly good when I heard "thank you" from a cyberspace either.

This issue may not be a good place for high-level discussions not concerning this api replacement. If considered useful, we can open a new issue dedicated for this.
For this feature, I do not see any additional maintainence burden, except for **understand the code once**. This point, on my own view, is necessary for any projects by more than one contributor.

**Comment by James-Yu** [comment]
Just double checked the previous PR. It is in fact simplifying the codebase and logic. I cannot convince myself the PR is bad, or at least has nothing to learn from.

**Comment by tamuratak** [comment]
I have said all I have to say. I will not reply on this issue any more.

**Comment by James-Yu** [comment]
> The customEditor API does not allow us to open the same document in the same editor group. That is the reason I rejected the PR as I explained.

@ManuelHentschel stated in his issue #3338 that opening the same document is still possible by "open the pdf in a new view column, by dragging the filename from the explorer view to the side of the currently open editor"

And "refocus an already opened pdf viewer by clicking on the filename in the explorer viewuse file icon themes"

This behavior is identical to what vscode provides to any other documents, such as `.tex` file. When you have a tex opened, clicking the file name in the explore reveals the already-opened editor. I do not see the reason `.pdf` files shall be handled differently.

@jlelong sorry for bother, but it seems that we are on two different sides wrt this issue. May I also call for your thoughts on this? I will take any responsibility.

**Comment by tamuratak** [comment]
Now that I have something to say. 

> @jlelong sorry for bother, but it seems that we are on two different sides wrt this issue. May I also call for your thoughts on this? I will take any responsibility.

Asking questions like that would imply that he would decide whether or not I would leave this project. I think such kind of your behavior is not morally respectable.

@James-Yu May I ask you a question? Are you willing to learn how to write good code and how to maintain OSS from me? 

For example, on the original PR, #3338, without opening an issue, a change to the basic architecture is proposed in addition to a change to some features. Opening such PR is considered to be a bad manner. Did you know that?

There are a lot of ways to implement the proposed change. However, you seem not to consider other implementations of the underlying feature? Did you consider another possible implementation? [I did, by the way](https://github.com/tamuratak/LaTeX-Workshop/tree/customeditor_pdfviewer_c).

I don't want to discuss with you every single one of the basic things of coding and maintaining OSS described above, but if you are willing to be taught, I will use my time to teach you. If you are not willing to be taught, I will leave the project because I do not want to spend time debating the pros and cons of such basics.

@James-Yu, are you willing to learn from me?

**Comment by James-Yu** [comment]
> Asking questions like that would imply that he would decide whether or not I would leave this project. I think such kind of your behavior is not morally respectable.

I sincerely apologize for my previous statement and the caused understanding. I was not in a correct mood and mind when I replied. Sorry.

Part 1, w.r.t. this PR and issue.

I believe in (or should have believed in) your code dev, architecture, and other software engineering-related skills. So this issue and PR are left as is for now. @ManuelHentschel Thanks very much for your code contribution, though maintainability is indeed a priority.

Part 2, w.r.t. issue and PR handling.

I myself is concerned on the future of LW. The project needs to be welcoming contributors or even extra maintainers. The current close and lock practice may not advocate a good communication with users or even potential code collaborators.

I fully understand that people may like or don't like dealing with reasonable or unreasonable issues/PRs, meaningful or senseless discussions. What I want to suggest is, is it possible to give more words on the reason of closing an issue or PR, so that the others may potentially learn from it? It's not anyone's obligation to explain, and it's also fine to just leave the issue or PR open for commenting. Just ignore it if don't want to response.

**Comment by tamuratak** [comment]
I see you don't answer my question with yes or no.

> Part 2, w.r.t. issue and PR handling.

Have we been discussing the issue and PR handling? If you are mainly interested in it rather than in the new API, you should have explicitly said so.

>  is it possible to give more words on the reason of closing an issue or PR, so that the others may potentially learn from it?

No. 

>  Just ignore it if don't want to response.

No.

> I myself is concerned on the future of LW. The project needs to be welcoming contributors or even extra maintainers. The current close and lock practice may not advocate a good communication with users or even potential code collaborators.

I think we have agreed that let us enable GitHub Discussions for that purpose. And I have never touched discussions on it.

I am not sure this is your main reason. Only because you are concerned about the future of this project? If there is any other reason, please say so.

As I said before, I never change my mind. I have seen lots of issues on a lot of repositories, not only on this repository. I have learned how users behave. I have concluded that locking issues is the best way to protect maintainers' mental health, which is easily hurt. I truly believe this is the best for that purpose. I truly believe justice is on my side.

So, if you force me not to lock issues, I will stop contributing to LaTeX Workshop as I said before. Discussing this topic, again and again, is also bad for my mental health. Please choose one of the current maintainers or potential future collaborators right now.

**Comment by James-Yu** [comment]
I am sorry the situation comes to this place and harms your mental health. Absolutely not my intention.

I am also sorry that I cannot agree with this locking issue philosophy and insist on mine. Let's stop the discussion here (or one more reply to this). Your decision on whether contributing to the project or not will be fully respected.
