### ISSUE TITLE
Make magic commands work by default

### ISSUE THREAD

**Issue by cbrnr** [James-Yu/LaTeX-Workshop#339]
I know that magic commands such as `% !TEX program = xelatex` are already supported, but they don't work out of the box. It seems like the reason is that the default command is set to `latexmk`. Would it be possible to keep using `latexmk` even in the presence of magic commands, but then call it with the appropriate argument `latexmk -xelatex` (or similarly, `latexmk -lualatex`)?

**Comment by James-Yu** [comment]
This one won't be possible, since the LaTeX world is still not ruled by `latexmk`. You suggestion (seems to be) can be interpret as adding appropriate argument based on the magic comment. However, the said argument can be different for `latexmk` and other automation tools, e.g., `arara`. What do you think?

**Comment by cbrnr** [comment]
I'm not sure, maybe this can be determined dynamically based on the tool. I just tried your plugin for the first time but I have to say that the Atom plugin just works - maybe it's worth trying to find out how they do it?
