### ISSUE TITLE
Completion of references from external document (`xr` package)

### ISSUE THREAD

**Issue by merlinND** [James-Yu/LaTeX-Workshop#3391]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you can not see the requested feature. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before requesting a feature.

You visited the wiki?: Yes

## Is your requested feature  related to a problem? Please describe. [Required]

When a document is setup to use references from another compiled LaTeX document using `xr`, the references work at compile time but are not suggested by autocomplete.

```
\usepackage{xr}
\externaldocument{other_document}
```

## To Reproduce  [Required]

1. Create a valid document `a.tex` with a label `\label{sec:example}`. Compile it.
2. Create a valid document `b.tex`. Use package `xr`'s `\externaldocument{a}` command to include labels from `a.tex`. Add a reference to `\ref{sec:example}`. Compile.
3. The document compiles correctly but label `sec:example` was not included in the autocomplete for `\ref{` in document `b.tex`.

## Describe the solution you'd like  [Required]

The set of all labels (sections, figures, equations, etc) would be included in the autocompletion of `\ref{` and `\autoref{`.
Ideally, there would be a new option in the extention configuration to enable or disable this.

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: macOS 11.6
 - VS Code version: 1.69.2
 - Extension version: 8.27.2
 - TeX distribution version: MacTex 2021

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

Yes (but the same issue occurs locally).

**Comment by James-Yu** [comment]
The extension does not support the package xr for now. There is no explicit plan on supporting it.

Other extension users may leave comments to this issue. We typically only optionally provide support to packages with a big userbase. Also subject to maintainers’ interest.

Lastly, PR welcomed!

**Comment by tamuratak** [comment]
You had better not say "PR welcomed" casually since maintaining the completion component is difficult. Due to the quality, pull requests would make it harder usually. If you want to welcome pull requests, what you have to do is to write comprehensive unit tests for the component. Even if you don't like to write tests, what you have to do doesn't change.

And, @jlelong has been maintaining the completion component, he should decide to implement the requested feature.

**Comment by jlelong** [comment]
This seems interesting. I will have a closer look.

**Comment by quoc-ho** [comment]
It's fantastic that the plugin now supports `xr`! I'm curious if it is possible for the autocompletion to work without the presence of the original `.tex` file of the "other" document. Namely, the package `xr` only requires the `.aux` file of the other document (and not the `.tex` file) to get the references correctly. However, for the plugin to work, we actually need the `.tex` file. Can we make it so that the `.aux` file alone is sufficient?

Thank you!

**Comment by James-Yu** [comment]
Not likely to be implemented, at least by me.
