### ISSUE TITLE
Incompatibility message somewhat unclear.

### ISSUE THREAD

**Issue by postylem** [James-Yu/LaTeX-Workshop#3683]
I have been using [vscode-pdf](https://github.com/tomoki1207/vscode-pdfviewer), and noticed that when I also use LaTeX-Workshop, I get the following warning message:

> LaTeX Workshop is incompatible with "vscode-pdf". Please consider disabling either lw.

My issue is just that the phrase "disabling either lw" is not clear (does this mean "disabling either vscode-pdf or LaTeX-Workshop"?).  Perhaps that warning message could be modified to be more clear?

My other comment is that I'd like to know what this incompatibility is.  I haven't noticed anything working unexpectedly, so I'm just curious whether it's necessary to warn users about this (I imagine that's just me not having noticed it yet, but I'm just curious).

https://github.com/James-Yu/LaTeX-Workshop/blob/da4b6a2f27998a63f4ccd1110a4b36f92a8a6e98/src/main.ts#L298

Thanks for the very useful extension!

**Comment by James-Yu** [comment]
Both issue resolved.

The extensions may conflict as both register file handler to *.pdf files. The other extension is obviously more lightweight, yet LaTeX-Workshop provides a more feature-rich viewer.

We created the warning a few years ago because the other extension lost maintenance for many years.
