### ISSUE TITLE
Feature Request: SyncTex support for 3rd party pdf viewers

### ISSUE THREAD

**Issue by Jo-Fleck** [James-Yu/LaTeX-Workshop#391]
Thanks a lot for developing this extension! I am fairly new to it so please apologize if I am duplicating. (Maybe an experienced user knows an easy fix to this issue which does not require an additional feature.)

Description of the issue:
I would like to work with two screens; one for the tex code, one for the pdf. I cannot drag the default tab to another screen since vscode does not feature floating windows. (Long story - seems unlikely they will come soon... https://github.com/Microsoft/vscode/issues/10121)

Possible solution:
Open the pdf in a 3rd party pdf viewer on the second screen. However, this kills the forward and backward SyncTex tools since they are only supported for the default pdf viewer (in the tab).

Is there a chance this feature could be added?

**Comment by James-Yu** [comment]
The `open PDF in web page` is designed for this. As to 3rd-party PDF viewer, this extension will not provide such support as been answered in many previous issues, since TBH there are too many/unlimited such viewers to support.

All in all, thanks for using the extension and hope open-in-web-page can fit your need.

**Comment by Jo-Fleck** [comment]
Excellent - this does the trick for me!

Thanks for all of your work on this!
