### ISSUE TITLE
Scanning of `label=` for intellisense

### ISSUE THREAD

**Issue by jlelong** [James-Yu/LaTeX-Workshop#4069]
This is related to jlelong/LaTeX-Workshop-wiki#111

It seems that commit 2c98d3b8a85c7f5b699503f3d05adb6e8a8c2187 narrowed the scanning of `label={...}` to the frame environment. However, as mentioned in #1878, the `listings` environment also relies on such a construction, see https://tex.stackexchange.com/a/122287. There may be other environments I am not aware of.

@James-Yu What was the reason for removing `latex-workshop.intellisense.label.keyval`?

**Comment by James-Yu** [comment]
All changes were made in favor of the different parsing by `unified-latex`, where `label={...}` in different places may appear as different components (args, content, or even verbatim). A good thing with `unified-latex` is, now it is trivial to distinguish `\begin{env}[label=123]` from `\textcolor{red}{label=123}`. But I forgot about `lstlistings` when implement that ...

So for the first question, the solution can be easy. What about removing the `frame` env check and parse all `label={...}` for the second argument of environments (as the first one is the environment name)?

In terms of removing the config, also because of the capability of `unified-latex`. Now the false-positives should be quite rare, even with this solution implemented. So it seems that the config is less necessary as almost all users can set it to `true` without worrying about `\node[label={123}]. What do you think?

**Comment by jlelong** [comment]
Thanks for the detailed explanation. I agree that we could simply restrict `label={...}` to the second argument of environments.
