### ISSUE TITLE
Intellisense sub or superscripted expressions

### ISSUE THREAD

**Issue by rahulshw** [James-Yu/LaTeX-Workshop#4159]
## Pre-checks*
- [ *] The feature request has not been suggested in this repository.

## The Missed*
- It does not suggest the full superscripted expressions. Some symbols involving subscript and superscript we use again an again, we have to write the full expression with all the underscores and barackets again and again. Previously in https://github.com/James-Yu/LaTeX-Workshop/issues/4118 the issue was raised but not fully resolved. If `$A_{\mu}^{a}$` is written anywhere in the text, I want the  the full expression `A_{\mu}^{a}` in the suggestion, not just the subscripts or superscript. 

## The Solution*
- Add the expressions with any subscript or superscript to intellisense

## Anything Else?
-

**Comment by James-Yu** [comment]
I'm happy to take this as an accepted request. This may take some time, though.

**Comment by James-Yu** [comment]
After checking the request, I have to unfortunately say this won't be implemented at least in the foreseeable future due to two limitations:
1. It is hard to develop a heuristic to detect the "base" of sub/superscripts. For instance, it is very common (though not advised) to write things like `$Pr_z(\cdot)$`. There is no known method to distinguish whether the `_z` is one for `Pr` or `r`.
2. The intellisense suggestion cannot distinguish between math mode or text mode on-the-fly. We can, but doing so in real-time is way too time-consuming.
