### ISSUE TITLE
Direct toolchain to run in specific terminal (e.g., to run through Windows Subsystem for Linux bash terminal)

### ISSUE THREAD

**Issue by zachjweiner** [James-Yu/LaTeX-Workshop#443]
I have TeXLive installed on my Ubuntu instance via the Windows Subsystem for Linux, and would love to route LaTeX Workshop through the WSL integrated terminal to compile there, rather than having to install LaTeX on the Windows side as well. Is this possible?

**Comment by James-Yu** [comment]
As far as I know, it is not possible. I'd glad to know ways to overcome this though.

**Comment by James-Yu** [comment]
[This SO question](https://stackoverflow.com/questions/46317030/how-to-call-linux-commands-through-wsl-in-windows-command-line) seems promising. I did not try it though.

**Comment by nikhilweee** [comment]
I'd love to have this implemented. Here are some things that I tried.
I have `latexmk` installed both in WSL and CMD through the following command.
```
tlmgr install latexmk
```
 Both of them work fine in their respective terminals.
```
WSL
$ latexmk
Latexmk: This is Latexmk, John Collins, 1 January 2015, version: 4.41.
Latexmk: All targets (report.dvi) are up-to-date
```
```
CMD
>latexmk
Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.

Latexmk: No file name specified, and I couldn't find any
Use
   latexmk -help
to get usage information
C:\texlive\2017\bin\win32\runscript.tlu:711: command failed with exit code 10:
perl.exe c:\texlive\2017\texmf-dist\scripts\latexmk\latexmk.pl
```
I can also run WSL's `latexmk` from CMD
```
CMD
>wsl latexmk
Latexmk: This is Latexmk, John Collins, 1 January 2015, version: 4.41.

Latexmk: No file name specified, and I couldn't find any
Use
   latexmk -help
to get usage information
```

But when I try to use the default toolchain, I get the following error in the logs.
```
"latex-workshop.latex.toolchain": [
        {
            "command": "latexmk",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "-pdf",
                "%DOC%"
            ]
        }
    ]
```
```
[10:23:57] LaTeX fatal error: spawn latexmk ENOENT, . Does the executable exist?
```
I tried the following variations in the `command` argument,, but none of them seem to work.
```
latexmk
latexmk.exe
wsl latexmk
```
How is it that `latexmk` works fine in the individual terminals (and even within each other), but fails from Latex Workshop?

**Comment by nikhilweee** [comment]
So I finally managed to use latexmk installed within WSL with the following toolchain.
```
    "latex-workshop.latex.toolchain": [
        {
            "command": "c:\\windows\\system32\\wsl.exe",
            "args": [
                "latexmk",
                "-synctex=1",
                // "-interaction=nonstopmode",
                "-pdf",
                // "%DOCFILE%"
            ]
        }
    ],
```

**Comment by micoloth** [comment]
Hello! I know that this issue is closed, but i'm writing here as i'm not able to make this solution work. Also,  in version 5 they changed `toolchain ` into `tools` so this fix is not entirely up to date yet.



My setup is: i have `latex workshop` installed straight from the marketplace, and `texlive-full` installed on wsl through `bash` `apt install`. This contains `latexmk `and `Synctex`. I can successfully build pdfs through the wsl command line, so the problem is the Latex Workshop tools call.


My version of the tools call (made by using the suggested migration) is:


```
"latex-workshop.latex.recipes": [{
        "name": "wsl",
        "tools": [
          "wsl"
        ]
      }],
      "latex-workshop.latex.tools": [{
          "name": "wsl",
          "command": "wsl.exe",
          "args": [
              "latexmk",
              "-synctex=1",
              "-interaction=nonstopmode",
              "-pdf"//,
              //"%DOC%.tex"
          ]
      }]
```



But the latex Workshop doesn't seem to pick it up. In particular, I can compile things from the command line so this wouldn't be a huge deal, but i _really_ would like `Synctex` to work.


Currently, when I click on a pdf in the pdf viewer, simply nothing happens.


If anyone could answer and suggest how to fix this, it would be hugely appreciated.
