### ISSUE TITLE
intellisence for entries in glossary

### ISSUE THREAD

**Issue by LeoJhonSong** [James-Yu/LaTeX-Workshop#4472]
Could we have intellisence for commands like `\gls{}` automatically completed with glossary entries stored in a `.bib` file, just like intellisence for commands like `\cite{}`?

Thank you vert much for the powerful extension!

A demo is given below👇
main.tex >
```latex
\documentclass{article}
\usepackage{glossaries-extra}
\GlsXtrLoadResources[
    src={symbols.bib},
]

\begin{document}
\gls{fs}, \gls{theta}
\end{document}
```
symbols.bib >
```bibtex
@symbol{fs,
  name        = {\ensuremath{f_s}},
  description = {sample rate}
},
@symbol{theta,
  name        = {\ensuremath{\theta}},
  description = {horizontal angle}
}
```

**Comment by jlelong** [comment]
Thanks for your feature request.

Actually, this is not an intellisense issue as we already have auto-completion for many glossary commands, such as `\gls`.  The problem is that the extension does not use the `\GlsXtrLoadResources` instruction to load the glossary related data. So implementing this feature request requires

1. First, to parse

     ```latex
     \GlsXtrLoadResources[
          src={symbols.bib},
     ]
    ```
    to resolve the path of `symbols.bib`

1. Then, to parse the content of `symbols.bib` to populate our glossary database. 

I have just checked that our `bib` parser can parse the `symbols.bib` file given as an example. 


@LeoJhonSong Do you have a reference document (or link) listing the keywords we can expect in `@symbol` entries? Are there other entries to consider? The more complete is the information, the easier and more efficient is the feature development.

**Comment by guger** [comment]
Nice work! I was just researching the same issue just to find it recently resolved. 🥳
Thank you all for your active work on this great extension!
