### ISSUE TITLE
Latest release has broken references/layout

### ISSUE THREAD

**Issue by kentcb** [James-Yu/LaTeX-Workshop#528]
### Description

As per #519, I have a document that built fine prior to 5.0.4, but now has problems. The fix for #519 allows me to build without any errors, but now I have different problems:

Firstly, a build does not correctly fill in references. The compiler output suggests building again.

Upon building again, I get other issues. First, part labels aren't resolving. It's strange, but they're displaying in the ToC with the correct names, but not when referenced throughout the document. Second, things are just really messed up. Sizes are clearly not resolving correctly, with headers and footers running off the page, and graphics not appearing the right spots.

Other things I've noticed:

* the first build produces 250 pages, the second produces 254 (I expect 254)
* the build seems to be a _lot_ faster than it was in the last working version I had. This makes me very suspicious.

I'm kinda desperate here. I would love to just roll back to the release prior to 5.0.4, but I don't know if that's possible...?

### Expected behavior

Document that built and looked fine prior to 5.0.4 continues to do so.

### Actual behavior

All sorts of problems per above.

### Log messages

Here are gists from [the first build](https://gist.github.com/kentcb/0f110d40440c249703dc0b14f7b14abf) and [the second build](https://gist.github.com/kentcb/1b23e29d073fe0a14ada7d2d25a9de7a).

### Additional Information

Windows 10.

**Comment by James-Yu** [comment]
Try remove the tex program magic comment.

**Comment by kentcb** [comment]
@James-Yu do you mean this:

```
% !TEX program = xelatex
```

If so, why? I want to build with xelatex. If I remove it, my build fails with:

```
! 
! The fontspec package requires either XeTeX or LuaTeX.
! 
! You must change your typesetting engine to, e.g., "xelatex" or
! "lualatex"instead of plain "latex" or "pdflatex".
```

**Comment by kentcb** [comment]
Sorry, but this is all very confusing, especially for someone who isn't very proficient in LaTeX, like me.

For starters, I don't understand why my issue has been closed. That suggests to me there is nothing wrong with the software, but I don't see an explanation as to why.

Also, Using `%!BIB program` has exactly the same problem: an error telling me I need to use `xelatex`.

Can you please enlighten me? Is this a problem with the extension or not? Does it no longer support `xelatex`? If so, why not? How can I get back to a working build that produces the same output as prior to 5.0.4?

**Comment by James-Yu** [comment]
Let me explain the whole system a bit. For all's reference.

First. LaTeX is a complex and cumbersome system that requires some study before using it.
Second. The good/best way of compiling a LaTeX project with the extension is to use its recipe (originally toolchain) system instead of the magic comment, which is only meant to be a backward compatibility feature.
Third. For any LaTeX document without bibliography, one pass compilation with `pdflatex`/`xelatex`/anything is good enough. However, when you have bibs in it, `bibtex`/`biber`/anything else is required, and the whole compilation becomes `some-latex` > `bib-something` > `some-latex` > `some-latex`.

OK let's come to your use case.

So obviously you have bibliographies in the document, and the four-pass method is the one. In the previous version, the extension will do so upon seeing `TeX` comment. However this causes trouble for those without bibs, since `bibtex` returns error on such documents. In the new version, `TeX` alone will lead to one-pass compilation. Only when both `TeX` and `BIB` are presented, the four-pass one is invoked.

---

I myself does not have any experience on using magic comments, even with other LaTeX editors. There is even surprisingly no document stating how they works under the hood. You can guess how frustrating it is to implement compatibility feature without documentation.

---

Some postscript gossip

@kentcb I totally understand your frustration as a new-comer into the LaTeX world. However, I would like to make you know that the magic comment things are never LaTeX. They are merely the result of some historical, un-configurable LaTeX editor. I don't know from which source the magic comment is recommended to you, but I'd suggest you take a look at the recipe system of this extension, or to have some knowledge on the LaTeX/bibTeX compilers (https://tex.stackexchange.com/ can be a good source).

---

Some post-postscript self-reflection

I myself is not a nice man good at explaining things to other on the web. It's my personal fault, not yours or the extension's.

**Comment by kentcb** [comment]
Thanks for the great explanation, @James-Yu - I really appreciate it.

> So obviously you have bibliographies in the document

Actually, I don't, which is why the 5.0.4 release broke my compile. 5.1.0 got me building again, since it didn't assume a bibliography, but broke me in other ways that are way beyond my ability to understand and fix.

> It seems that the README is quite outdated w.r.t. the magic comment part. It will be updated soon.

Thanks. It's also outdated in terms of how to manually install the extension, as I found early today. Instead of copying files in, you need to use a VSIX. I ended up tracking down and manually downloading 3.14.0 from [here](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/James-Yu/vsextensions/latex-workshop/3.14.0/vspackage), uninstalling the new version, disabling Internet on my laptop (so VSCode would not update the extension!), then installing manually via the Extensions menu in VSCode.

Not ideal, I know, but it got me back to a working build. The thing is, I have a book to release this week. Something I've spent literally months working on, without any prior knowledge of LaTeX. So I just got it working how I could using the advice I could find at the time. Sounds like it's definitely not an ideal approach, so lesson learned there for me. And totally no fault of yours that you have to deal with such a fragile and hacky LaTeX ecosystem, or that VSCode does not easily allow extension updates to be rolled back or withheld.

Anyway, it sounds like the right approach would be for me to remove the magic comments and use recipes to execute the correct tooling instead. Given my timeframes, I'll stick with 3.14.0 for now and play around with that after the launch of my book.

Thanks for all your hard work, James. It would have taken me a lot longer to typeset my book if I didn't have this great extension ❤️

**Comment by James-Yu** [comment]
I've double checked your logs and confirm that there's no bibs. It seems that `xelatex` is messing up your document. You can try this command in terminal/CMD `xelatex yourfile.tex` and see what's going on.

The extension only calls such commands under the hood. It does not manipulate how the compile would typeset/arrange where things go/link hyper-references.
