### ISSUE TITLE
How to use the synctex?

### ISSUE THREAD

**Issue by kamalhm** [James-Yu/LaTeX-Workshop#541]
I've built my latex project, then i view the pdf in vs code tab, then how can I use the synctex? i tried double clicking on the text on the pdf, nothing, tried to right click and 'syntex from cursor' also still nothing

**Comment by James-Yu** [comment]
did you install synctex?

**Comment by junyuan-chen** [comment]
I can use synctex from the source code to match with the pdf. But, I cannot do that in the opposite direction. Is it supposed to work by just clicking on the pdf?

**Comment by kamalhm** [comment]
yes i did installed synctex

**Comment by sbacelar** [comment]
I know this is closed but I have the same problem. I use a Mac. Is it possible to explain better how to use synctex? I had no problem with it with TexShop in the same machine.

**Comment by tamuratak** [comment]
See https://github.com/James-Yu/LaTeX-Workshop/wiki/View

**Comment by sbacelar** [comment]
Yes, I have read the wiki/View page before. But I think I have discovered later at least part of the problem: I was using `Skim` as my external pdf viewer and `synctex` was not working. When I use `Vscode Tab` as my default internal viewer almost works well: I can go from the `tex` file to `pdf` and from `pdf` to `tex` file (but in this last case it also opens --I don't know exactly how it is called -- a first left column with the "main commands" and I don't want it to do this because I see only part of `tex`file).

**Comment by tamuratak** [comment]
External pdf viewers are not officially supported. 

If you have a problem with the internal pdf viewer, please open a new issue.
