### ISSUE TITLE
pdf error for two short sequence of `ctrl+s`

### ISSUE THREAD

**Issue by innerlee** [James-Yu/LaTeX-Workshop#556]
will investigate this later.

**Comment by bnord01** [comment]
Any save during an active build leads to a warning popup `Recipe terminated with [an] error. Retry building the project.` and most of the time an invalid pdf is produced. The only error I see in the _latexmk_ output is `SyncTeX: Can't rename main.synctex.gz(busy) to main.synctex.gz`. 

The suggested rebuilding of the project doesn't work as the pdf is up to date according to _latexmk_. In order to recover from this one needs to change a source file and trigger another build.

I guess the problem is, that there are two builds running concurrently on the same auxiliary files which most probably isn't supported by _latexmk_. Triggering a new build (manually or automagically) should probably either terminate any running build first or wait for it to finish. I can produce the same invalid PDF when triggering a build through LaTeX Workshop while an external _latexmk_ command is running.
