### ISSUE TITLE
Refresh PDF after build finish

### ISSUE THREAD

**Issue by vomout** [James-Yu/LaTeX-Workshop#613]
### Description

Currently, at least when Skim is used as PDF viewer following a comment in #318, the viewer is not instructed to update the file *and* move to the correct location when build is finished.  The correct location would be where the cursor was when the build was triggered with ctrl-alt-b. (This is, for example, what LaTeXTools of SublimeText does.) Instead one has to waste time and consciously wait for the build to finish, and then view the correct location using ctrl-alt-v. If not default behaviour, there should be at least an option to enable this behaviour. 

### Log messages

Not relevant—issue appears a feature request.

### How to reproduce

1. Follow a comment in #318 to enable Skim as viewer. (Possibly not required.)
2. Build the file with ctrl-alt-b at some location.
3. Observe that the viewer does not switch to the correct location upon finishing the build.

### Expected behavior

Viewer should switch to the location where the build was triggered. 

### Actual behavior

Nothing (upon the build finishing), unless Skim is configured to check for file changes. But then it does not switch to the correct location, as it is not being instructed by LaTeX-Workshop to do so.

**Comment by James-Yu** [comment]
The behavior for built-in viewer is to retain where the scrollbar was left.

It seems that auto-call synctex after build is easy enough. However, the built-in viewer requires some time to render the new PDF file, during which time it can be unresponsive to synctex instructions. I will briefly check if it can be avoided, otherwise I have to say sorry to this feature request.

**Comment by vomout** [comment]
Yeah, I immediately opted not to use the built-in viewer because it loads very slowly on refresh. Also I couldn't just drag and drop to create a new window for split screen. But to be fair I didn't try to create a completely new VScode window and place the PDF there, or to see if there's a split mode, as I don't generally work with apps full-screened to have better access to the terminal etc.

**Comment by dsteg** [comment]
@vomout: it is indeed quite surprising how slow the internal PDF viewer is compared to Skim. I did some timings: it is slower by (at least) a factor of 4

**Comment by James-Yu** [comment]
Blame `PDF.js`.

Just kidding. This is due to the relatively slow execution speed of javascript compared with native code. It seems inevitable until a more mature embed-able PDF viewer appeared.

**Comment by linhtto** [comment]
@James-Yu , I see that  "latex-workshop.synctex.afterBuild.enabled" can now be set, but it doesn't seem to actually do what it's meant to do for me, because at the end I just get this:
`[14:45:54] Successfully built /file.tex`
`[14:45:54] No PDF viewer connected for /file.pdf`

@vomout, did you test this out as well and can maybe share your experience?

**Comment by linhtto** [comment]
This is an attempt to look more closely at this with my very limited knowledge:

@James-Yu , I think the error I got above (No PDF viewer connected) is separate from the fact that syncTeX didn't actually get implemented upon completion of the build.

1. The error comes from the line `this.extension.viewer.refreshExistingViewer(rootFile);` in `buildFinished(rootfile)` in `builder.ts`. I'm not sure why.
2. I can get syncTeX to be called as in the desired behavior described in this issue when adding these lines to the end of `buildFinished(rootfile)` in `builder.ts`:
```
if (configuration.get('synctex.afterBuild.enabled')) {
                        this.extension.locator.syncTeX();
                    }
```

**Comment by StevenLi-DS** [comment]
I sometimes refresh my PDF viewer during the build, and then I'll get the following error.

<img width="343" alt="Snipaste_398" src="https://user-images.githubusercontent.com/33796896/69670047-06ca1300-1061-11ea-9789-8ed90c1f84c0.png">

I have to wait the build to finish first and then refresh so that the PDF can be displayed, but the problem is that it will reload the PDF and won't be back to the page I was at. 

Is this related to this issue? I think maybe the extension should wait for the build to finish itself rather than requiring users to check the build status first whenever they wanna refresh.

**Comment by jlelong** [comment]
When the build is not finished, refreshing may try to load a corrupted PDF file, hence the error. The PDF is automatically refreshed after build, so I cannot really understand the issue here.

**Comment by StevenLi-DS** [comment]
Automatically refresh? I didn't know that. Is there any toggle I have to set or something?

**Comment by vomout** [comment]
It's a simple one-line fix: https://github.com/vomout/LaTeX-Workshop_sanity/commit/55ffe28624077d3f40f930b031c97a401577f8da

**Comment by jlelong** [comment]
@StevenLi-DS From your screenshot it looks like you are using the internal PDF viewer (inside VSCode), aren't you? If so, can you please post the logs of the extension (OUTPUT pane / LaTeX Workshop) to investigate what is going on?

**Comment by StevenLi-DS** [comment]
@jlelong Maybe, I'm not quite sure about that. Is there anyway I can convert to LaTex Workshop viewer or something?

**Comment by jlelong** [comment]
Can you please post the logs of the extension (OUTPUT pane / LaTeX Workshop) to try to understand what is going on. Do you view the PDF file inside VSCode?

**Comment by StevenLi-DS** [comment]
@jlelong sorry about that. please see the logs below

[log.txt](https://github.com/James-Yu/LaTeX-Workshop/files/3900608/log.txt)
[random.log](https://github.com/James-Yu/LaTeX-Workshop/files/3900609/random.log)

I do think I use the pdf viewer inside vscode.
![Snipaste_228](https://user-images.githubusercontent.com/33796896/69789594-dc767380-118e-11ea-948f-783abfc9273f.png)
