### ISSUE TITLE
latexindent doesn't work "on save"

### ISSUE THREAD

**Issue by mcoweber** [James-Yu/LaTeX-Workshop#644]
Hi,

I'm using latexindent to automatically format my LaTeX files. After some struggle during installation I got it to work. However, only if I right-click and select "Format document".
Although I have ""editor.formatOnSave": true", the document is not formatted on save. Furthermore, the LaTeX Workshop Output says "Formatted -filename-" but nothing happens (same output as for right-click -> "Format document" with the difference that it works in this case).

Some system information:
- Windows 10
- MiKTeX 2.9
- ActivePerl 5.24.3

Best regards
Marc

**Comment by James-Yu** [comment]
If right-click format works, it is not an issue of this extension. You may need to resort to vscode/latexindent or related repo for more information.

**Comment by mcoweber** [comment]
Hi James,

I don't wanna re-open the issue, but what is the difference between right-click formatting and "on save". Is latexindent invoked in different ways? Has it to be registered separately/in a special way to work "on save" as well?
If you aren't the right person to ask, do you have a link for me where I can ask the question?

Best regards
Marc

**Comment by James-Yu** [comment]
The point is there is no difference at all between these two approaches. That is how I conclude that its not related to the extension.

I have no idea on who is the right guy. You may try https://github.com/Microsoft/vscode/ or latexindent repo, which I don't have access.

**Comment by mcoweber** [comment]
Thanks!

**Comment by mcoweber** [comment]
Already got an answer from Microsoft: https://github.com/Microsoft/vscode/issues/50345
Also, I can reproduce the issue on several machines (Win 7 and Win 10) as well as on a clean reinstall.
Can you reopen the issue?

**Comment by mcreng** [comment]
Hi all. I have been facing the same problem and here is a fix that works for me.

I believe the issue is caused by the configuration of latexindent in Latex Workshop plugin. The default settings for it is:
```json
  "latex-workshop.latexindent.args": [
    "-c",
    "%DIR%/",
    "%TMPFILE%",
    "-y=\"defaultIndent: '%INDENT%'\""
  ],
```
which I believe does not actually write back the formated file to your `%DOC%`.
Hence, modifying it to:
```json
  "latex-workshop.latexindent.args": [
    "-w",
    "%DOC%.tex",
    "-c",
    "%DIR%/",
    "%TMPFILE%",
    "-y=\"defaultIndent: '%INDENT%'\""
  ],
```
fixes the issue, where the argument `-w %DOC%.tex` actually would overwrite the formatted file back to your original file (as mentioned [here](https://latexindentpl.readthedocs.io/en/latest/sec-how-to-use.html))

Though after doing so, I encountered another problem, which is after saving the file, latexindent tries to overwrite the file and also latexmk tries to build the file at the same time, Iatexmk couldn't build the file because of the conflict at first run and it needs to retry before the file can be successfully built. Hence, to fix this, we can add the following to the settings:
```javascript
  "latex-workshop.latex.recipes": [
    {
      "name": "latexmk",
      "tools": [
        "latexindent",
        "latexmk"
      ]
    },
  // skipping the other recipes
  ],
  "latex-workshop.latex.tools": [
    {
      "name": "latexindent",
      "command": "latexindent",
      "args": [
        "-w",
        "%DOC%.tex",
        "-c",
        "%DIR%/",
        "%TMPFILE%",
        "-y=\"defaultIndent: '%INDENT%'\""
      ],
    },
  // skipping the other tools
  ],
```
which means before we run latexmk, we run latexindent first. We need to add latexindent to `latex-workshop.latex.tools` for it to recognize in the recipe. I believe the same can be done for the other recipes but I haven't tried them out.

Just remember to disable latex format on save after configuring the stuff above.
```json
  "[latex]": {
    "editor.formatOnSave": false
  },
```

**Comment by marmistrz** [comment]
For me the @mcreng's solution resulted in an infinite loop of builds.

**Comment by jlelong** [comment]
See [here](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#format-on-save-does-not-work) and [there](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#my-file-gets-messed-up).

This is probably related to a bad interplay between format on save and build on file change.

**Comment by qdm12** [comment]
Thanks @mcreng your solution worked for me! Is there a particular reason the default settings for latexindent are not working out of the box?

**Comment by tamuratak** [comment]
Please open a new issue filling out all the information required in the issue template.

**Comment by tamuratak** [comment]
Hide an outdated setting. See https://github.com/James-Yu/LaTeX-Workshop/issues/2178#issuecomment-650488433
