### ISSUE TITLE
Reference autocompletion should replace whole reference with found reference

### ISSUE THREAD

**Issue by chbndrhnns** [James-Yu/LaTeX-Workshop#661]
### Description

When I use the autocomplete feature for references, I often start typing what I think the reference is called and hit enter once it appears in the dropdown list. Then, what I already typed is replaced except if I enter something like `tab:table-bla` which is autocompleted to `tab:tab:table-bla` and leads to a reference error.

### Log messages

None

### How to reproduce

1. Write `\label{tab:reqs-lang-status}` in latex document
2. write `\autoref{tab:re` to see matching autocomplete entries
3. Hit Enter to accept it

### Expected behavior

The correct reference is put after \autoref{

### Actual behavior 

The reference looks like `tab:tab:reqs-lang-status`

**Comment by James-Yu** [comment]
This is a known issue. Unfortunately, labels with `-` or `:` are interpreted as multiple labels by vscode. This seems not to be a programmable behavior from the extension side. You are encouraged to submit an issue on vscode's repo.

tl,dr; sorry we cannot fix it on our side.

**Comment by jlelong** [comment]
It does actually work as expected on my installation even with labels containing `:` or `-`.

The only way I managed to reproduce the problem is 
1. start typing `\autoref{tab:re` 
1. Delete at least one character
1. Trigger intellisense using `^space`
1. Select `tab:reqs-lang-status` in the list
You end up with `\autoref{tab:tab:reqs-lang-status}`.

Can you tell use what is your configuration related to `suggestions`?

**Comment by chbndrhnns** [comment]
I noticed the same and was sure that the issue existed for months. I upgraded to VS Code 1.24 today. Maybe this resolved the issue?

**Comment by chbndrhnns** [comment]
I could trigger the behaviour, as well, by putting "moving the cursor left or right" as the second step in your reproduction step list.
