### ISSUE TITLE
[Feature Request] Forward synctex with Ctrl+LeftClick

### ISSUE THREAD

**Issue by Astrantia** [James-Yu/LaTeX-Workshop#716]
Reverse synctex currently supports this. What about forward synctex?

**Comment by James-Yu** [comment]
Not possible since vscode does not provide related API.

**Comment by GNHua** [comment]
Now one needs to right click and select `SyncTex from cursor` to go from tex file to pdf file. 
Is there any way to define a shortcut or hotkey for that?

**Comment by carstenhag** [comment]
Can we request this upstream? I am also looking for this feature.

Ctrl/Command-Click on .tex source to get forward synctex.

**Comment by carstenhag** [comment]
@GNHua I'm pretty sure you can define a hot-key to run `latex-workshop.synctex`, it's probably that command.

https://github.com/James-Yu/LaTeX-Workshop/blob/master/package.json#L37

**Comment by carstenhag** [comment]
@James-Yu Could this perhaps be implemented with this? 

https://code.visualstudio.com/docs/editor/editingevolved#_go-to-definition

**Comment by James-Yu** [comment]
@carstenhag The extension already has go-to-definition on labels. Re-assigning it to synctex will 1) break the feature 2) make it troublesome for systems without synctex. An upstream request is absolutely good, yet I myself doubt if the core team would adopt it.

**Comment by aterenin** [comment]
I'm also looking for this feature, which I think would prove extremely popular. I would gladly give up the ability to go-to-definition on labels to have working forward synctex via click. Perhaps this could be considered as an option that the user needs to enable?

Related: the right-click option for synctex appears to have been removed since the time this issue was created.

Also related: there's an upstream VS Code issue for customizing mouse click keybindings at https://github.com/microsoft/vscode/issues/3130.

**Comment by jlelong** [comment]
To get the right click menu back, set `latex-workshop.showContextMenu: true`.
Forward synctex is also accessible via a keybinding  `alt`+`cltr`+`j`.
