### ISSUE TITLE
propose latest open environment for `\end{` in autocompletion

### ISSUE THREAD

**Issue by alexanderadam** [James-Yu/LaTeX-Workshop#728]
### Description

I had this features in some LaTeX IDEs:

when closing an environment by writing the `end` command, the currently open environments where proposed for autocompletion

### How to reproduce

1. Write something like
```latex
\begin{batman}
  Bruce Wayne…
\end{
```
2. It proposes a lot of non-open environments but certainly not `batman`.

### Expected behavior

It proposes `batman`

### Actual behavior

It doesn't propose `batman`

### Additional Information

I love this extension! Thank you for your work!

**Comment by jlelong** [comment]
The extension already provides a workaround to your problem.
Instead of typing `\end{`, just call _LaTeX Workshop: Close current environment_ from the Command Palette and it will automatically insert `\end{batman}`. If you prefer, you can add a keybinding for `latex-workshop.close-env` and directly use it to close the most recently open environment.

**Comment by alexanderadam** [comment]
Hey @jlelong,

thank you for responding so fast.
Your response isn't at all what this issue is about, however.

What I meant is the _visual_ behaviour you see when you type.
It's about the functionality you see here in the screenshot:

![screenshot_20180802_201707](https://user-images.githubusercontent.com/372620/43602759-2eafdd3c-9691-11e8-9624-fb6ada45a0f6.png)

As you can see the suggestions here are pretty pointless because it proposes a long list of environments to close. In this list _none_ of these environments are open and _the only_ environment that actually is open is **not** in the list.

Therefore you can clearly say, that all suggestions are _wrong_. And not helpful.

**Comment by jlelong** [comment]
The real issue is that you should not come up with typing `\end{}` yourself as the extension provides a `\begin ... \end` snippet or you can use `latex-workshop.close-env` to close the current environment.

I cannot see the point of wanting autocompletion for `\end{}` as the only possible completion is the most recently opened environment which is precisely what `latex-workshop.close-env` does.

**Comment by alexanderadam** [comment]
Well, what is the point in the current implementation with the mega suggestion list of false environments then?

**Comment by jlelong** [comment]
As far as completion is concerned, `\begin` and `\end` are handled similarly. Hence, the long list you get is the list of environments known by the extension.

**Comment by alexanderadam** [comment]
Well, yes absolutely it seems like they are handled similar. Which is _exactly_ what is wrong and what is described in this issue. :wink:

Opening and closing commands are _obviously_ not the same. You can open any environment but you can only close environments that are open.

**Comment by alexanderadam** [comment]
So can we summarize here that this issue will be reopened because the [mentioned workaround](#issuecomment-409957084) has actually nothing with the wrongly behaving autocompletion?
