### ISSUE TITLE
PDF tab auto refresh on file change by external build tool

### ISSUE THREAD

**Issue by Nabav** [James-Yu/LaTeX-Workshop#749]
### Description

I use an _external Makefile_ and build the Latex project by a task in VSCode. The PDF file is generated externally, but it is not refreshed in preview tab. I need to run the command `latex-workshop.tab`, after build completion manually to see the fresh PDF.

### How to reproduce

1. Provide a Latex project with Makefile and create a build task in VSCode to run `make`,
2. Press `Ctrl+Shift+B` to build the project, and
3. (needed to be automated on task completion or file change) Run the command `latex-workshop.tab`

### Expected behavior

It would be great if the PDF tab is refreshed just after task completion or file change on disk.

### Additional Information

VSCode ver 1.26.0
LaTeX Workshop v5.8.2

**Comment by jlelong** [comment]
It should update automatically. Can you give us the output of the extension?

**Comment by raikesy** [comment]
@Nabav I believe you can fix your issue by creating a Latex Workshop recipe to run `make` instead of a VS Code build task. You can then call it with `Ctrl+Alt+B` and the tab should refresh.

On that vein though, I would like to request the PDF tab update when the file changes on disk. I am using the integrated terminal to test some different build commands and parameters and currently I have to run the command, refocus the editor window and then `Ctrl+Alt+V` to refresh the PDF tab. Really this should be automatic and instantaneous.

Currently it seems that LW only refreshes the PDF tab when its build recipe is called.

**Comment by Nabav** [comment]
> It should update automatically. Can you give us the output of the extension?

Since I am not running the LW recipe, it does not generate any output.

**Comment by Nabav** [comment]
> @Nabav I believe you can fix your issue by creating a Latex Workshop recipe to run `make` instead of a VS Code build task. You can then call it with `Ctrl+Alt+B` and the tab should refresh.

@raikesy I have made a new tool to run `make all` and a new recipe to run this tool at the first position. Now, I just press `Ctrl+Alt+B`, the Makefile process is followed and the PDF Tab is auto updated.
Thanks for the help.

**Comment by ashgillman** [comment]
As @raikesy suggests, auto reload on file change would be a useful feature. I'd propose that this issue be reopened.

**Comment by jlelong** [comment]
I am not sure this is as easy as it looks because a failing `latex` compilation often creates a corrupted `pdf` file. So if we refresh the viewer whenever the `pdf` changes, we may end up loading a corrupted `pdf` file and this will probably require to close and restart vscode to have it work again.

**Comment by ashgillman** [comment]
I don't think LaTeX writes to the output file unless it completes successfully. My usual workflow on Linux is to have a script that uses inotify to rerun Make whenever a file changes. Make then rebuilds the pdf. All the while, a PDF viewer with automatic reloading capability (Zathura usually, but also Evince) has the file open. I've never had a problem with corrupt PDFs.

I've recently moved to Windows and VS Code, but that solution doesn't work as Adobe Reader puts a read-write block on the file when you open it.
