### ISSUE TITLE
More Detail to Citation Autocomplete

### ISSUE THREAD

**Issue by jsinglet** [James-Yu/LaTeX-Workshop#90]
Often times the citation key isn't enough to identify a citation. What would be really helpful, rather than the citation key, would be an abbreviated version of the full BibTeX entry. At a minimum:

citation key: 
Authors, Year in: Publication
Title

Being able to narrow this with typing would be ideal. If this is not underway I may be able to help with this feature.

**Comment by James-Yu** [comment]
Now you can use author names, title, and citation key to filter the autocomplete items. The detailed information is in the blue information icon. I did not quite get what you mean by 'abbreviated version'. Can you please elaborate more?

![image](https://cloud.githubusercontent.com/assets/4210342/24734261/f7fad4cc-1aae-11e7-93f8-d9c4f6fb7995.png)

**Comment by jsinglet** [comment]
Ah, I just updated and now I see that. However, I still can't see the titles. Like in your screenshot they are cut off (as well as the author information). Is there a way to be able to see more?

**Comment by James-Yu** [comment]
The autocomplete window width is fixed in vscode. Alternative suggestions are always welcomed.

**Comment by jsinglet** [comment]
https://github.com/Microsoft/vscode/issues/369  

Oh my....

**Comment by James-Yu** [comment]
Yes it seems the final solution they worked out was the blue icon. Unfortunately it seems that we cannot modify it on the extension side. 😢

**Comment by jabooth** [comment]
Yeah when I implemented this richer citation intellisense I was a little frustrated at these restrictions. 

#### Current mitigations

**1.** we have implemented it so that although you might not be able to *see* all the information, you can still filter based on all the info. By that I mean if you know you are looking for the paper:

 _Why is it that all research papers have pathologically long titles: a study_

and you remember 'pathologically' being in the title, you should be able to do:
```
\cite{patho
```` 
And even if the key is `booth2006unrelated` the entry should still show up.

**2.** `cmd` / `ctrl` + `space` triggers the exanded info from the keyboard rather than hitting the blue i.


#### Other ideas - Citation Browser

In addition to the current intellisense feature, we could have a model window for citations that drops down from the top of VS Code. I was thinking we could call it something like `Citation Browser` - you could trigger it whenever you want to hunt down a specific citation in a window where we will be able to show more info.

I was thinking we could do this using whatever API we currently use for the `Latex Workshop Actions` panel.

#### Other ideas - Rearrange info

We could change what info is given most precedence in the autocomplete window, and let it be cusomized as a user preference. For instance, a user might opt into just showing the title in the intellisense window as that's what they are always looking for. Of course you could always expand the window to see all the info, the filtering would still work based on everything, and the citation key is always the thing that is inserted.

**Comment by James-Yu** [comment]
Both ideas are great! Will implement soon (TM)

**Comment by James-Yu** [comment]
The new PR should address this problem better. Close this issue for now. Discussion always welcomed!
