### ISSUE TITLE
Using --max-print-lines is not a fix for the log probems

### ISSUE THREAD

**Issue by thaney071** [James-Yu/LaTeX-Workshop#923]
I have left several comments on closed cases, but am not sure how likely they will be seen.

Recent changes made it so the `--max-print-lines` option is auto added to commands. See #885, #796. This is not a fix for the problem. This option is not supported by all latex compile tools and it is bad practice to manipulate the users command like this without them knowing. 

I have read several places where it was suggested as a way to fix thing not showing up in the logs, but when I noticed that I was able to find where the log parsing regexes are and fix it by making them less strict. I have never uses a latex editor that has to add this option for the logs to be parsed.

The root of the problems pane not showing log error, warnings and info is due to the regex patterns in the parser.ts.  I made mention in #866 to see how texstudios parses the logs as reference.

**Comment by jlelong** [comment]
The root of the problem is that `latex` compiler produce logs truncated at 80 characters. All editor extensions first have to unwrap the log to parse it, which proves to be a tough task and ends up in piling up regex and if conditions. To try to circumvent this delicate problem, we thought it would be much better to produce unwrapped logs directly.

There exists an environment variable to fix the line width for log, `max_print_line`, unfortunately some LaTeX compilers do not honor it, hence the `--max-print-lines`. 

1. Can you tell us what compiler you use?
1. I will move the extra `--max-print-lines` to a configuration variable of the extension.

**Comment by jlelong** [comment]
See the `latex-workshop.maxPrintLine.option.enabled` configuration option and the [related section of the README file](https://github.com/James-Yu/LaTeX-Workshop#problem-panel-and---max-print-lines)
